### ISSUE TITLE
Issue When Adding A New Airport

### ISSUE THREAD

**Issue by seanleppert** [jpatokal/openflights#1021]
After typing in all airport information, I am prompted to select a country. But the options for country is "ALL" and that's it. I cannot select anything else and the website won't let me use "ALL" as an option, so I cannot add the airport.

**Comment by MarkTownley** [comment]
Hi Sean
You closed this - I assume you solved it. How?

**Comment by seanleppert** [comment]
Hey Mark,

I haven’t solved this, I opened another issue on the page after donating to
it with hopes that it would get priority, but it seems as if nobody is
actively trying to solve the issues. So unfortunately, I’m probably not
going to use openflights anymore until it’s solved. Very unfortunate
because it’s a great site.

-Sean Leppert
