### ISSUE TITLE
Updating the Airline routes data

### ISSUE THREAD

**Issue by jrmistry** [jpatokal/openflights#1026]
Hello,

Sorry for posting a message here like this, I didn't know how else to contact the person/team managing openflights. I wanted to know what the schedule is for updating the airline routes data? If there is no current plan, then I have a way in mind that I would like to try. Let me know if you are interested to work together.

Jaydeep

**Comment by chrisrosset** [comment]
There is no set schedule and, at this point, it has been years since an update was posted.

I realize it's been 3 years since this was opened but if you're still interested, please post here and I'll re-open.
