### ISSUE TITLE
[Bug] Wrong behavior of the airport suggestion box [sf#103]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#103]
**Reported by strainu on 2011-06-09 13:28 UTC**
Add a new flight. Write "SVO" in the "From" edit box. A small suggestion box appears, which contains SVo and SVJ airports. Delete the text from the textbox and write BUH. The suggestion box does not change. At every new letter, the focus changes from one airport to the other, even if none of them contains that particular text.

**Comment by jpatokal** [comment]
**Commented by strainu on 2011-06-09 13:29 UTC**
This might happen to other suggestion boxes, I did not have time to check.

**Comment by chrisrosset** [comment]
This issue is 12 years old and I cannot reproduce this on the current website. I believe it's been resolved since. We also have a new autocomplete system that's pending release.
