### ISSUE TITLE
Adding an airport

### ISSUE THREAD

**Issue by SagyPM** [jpatokal/openflights#1034]
I'm trying to add JRS/LLJR airport and The form doesn't let me add it since the drop-down for country name only has the "ALL" option. I verified that I'm logged in and this was done when trying to add a flight record to my account.

Seem to be the same issue reported in [issue #1022 ](https://github.com/jpatokal/openflights/issues/1022#issue-581795039)

**Comment by lenny425** [comment]
I was able to get around this by manually adding my country to the dropdown menu

**Comment by SagyPM** [comment]
@lenny425, thanks for the suggestion, which browser are you using? I tied FireFox and Chrome, on both I'm unable to type in the country. It is a drop down field and the only option I get is "ALL". Even after a loading an airport the only option in the drop down is "ALL". I'm also unable to select anything other than "ALL" if I want to search for airports in a specific country.

**Comment by reedy** [comment]
#1087
