### ISSUE TITLE
Trying to add airports

### ISSUE THREAD

**Issue by jwer798** [jpatokal/openflights#1039]
Trying to add airports on openflights.org but does not give me the option to pick a country.  Only has ALL as an option.  Tried all three databases to add to, and it does not work.

**Comment by artshellone** [comment]
I had the same experience as well.  

I was trying to add a port: Montevideo, UY

**Comment by jwer798** [comment]
Can someone fix?  The error every time at the bottom is also "Results NaN to NaN of "

**Comment by Paguzur** [comment]
Exactly the same problem, trying to add IATA: BOP, ICAO: FEFO

**Comment by reedy** [comment]
#1087
