### ISSUE TITLE
Adding Airlines is not possible

### ISSUE THREAD

**Issue by sandrob95** [jpatokal/openflights#1045]
Would like add an Airlines, but I can't select a country, it only shows "ALL". I use Firefox
![Bild_1](https://user-images.githubusercontent.com/80889840/111609715-dd477480-87da-11eb-8c5b-369f687b564d.PNG)
![Bild_2](https://user-images.githubusercontent.com/80889840/111609721-dde00b00-87da-11eb-8d0f-1774d20539b2.PNG)

**Comment by 2sylbl** [comment]
I'm having this same issue on Chrome 92.x - The only country shown is 'ALL' and I get the same error shown in the screenshot.

**Comment by seanhsiung94** [comment]
I have observed identical issues. Is there a plan to address this issue?

**Comment by reedy** [comment]
#1087
