### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [jpatokal/openflights#1056]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by michaellrowley** [comment]
Any update on this?
The report referenced above can be viewed at https://huntr.dev/bounties/2fe489b0-18b1-47dc-92db-e631c42bd04a/

**Comment by reedy** [comment]
> Any update on this? The report referenced above can be viewed at https://huntr.dev/bounties/2fe489b0-18b1-47dc-92db-e631c42bd04a/

Unfortunately not public... How does someone get access to it to potentially address the issue?

**Comment by psmoros** [comment]
We got the email!! Feel free to close this issue
