### ISSUE TITLE
Required PHP Version?

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1083]
https://github.com/jpatokal/openflights/blob/master/INSTALL suggests Ubuntu 14.04 and then to install PHP5.

But https://github.com/jpatokal/openflights/blob/master/php/locale.php#L2 is PHP 7.3 code as per https://www.php.net/manual/en/function.session-set-cookie-params.php done in https://github.com/jpatokal/openflights/commit/e8844bfe8c5b9d40652f4061e9e28cf776c30904

**Comment by reedy** [comment]
```
$ curl -I https://openflights.org/ | grep x-powered-by
x-powered-by: PHP/5.5.9-1ubuntu4.29
```

**Comment by jpatokal** [comment]
The current recommended version is PHP 7.4.  (PHP 8 is known not to work.)  `INSTALL` has been updated.
