### ISSUE TITLE
Backup to csv doesn't work

### ISSUE THREAD

**Issue by dpupkov** [jpatokal/openflights#1086]
When trying to export data to csv from Settings nothing happens in Chrome. 

Root cause: function backupFlights() is trying to redirect from https to http. Such behaviour is blocked in many modern browsers.

From https://openflights.org/js/settings.js :

`// Need to duplicate this from openflights.js so that it opens in Settings window, not main, and
// IE does not go nuts
function backupFlights() {
  location.href="http://" + location.host + "/php/flights.php?export=backup";
}`

Suggested changing here http to https.

**Comment by jpatokal** [comment]
CSV backups were working from the main UI, but not the Settings page.  Fixed, thanks!
