### ISSUE TITLE
Cannot add new Airline

### ISSUE THREAD

**Issue by knotpestetot** [jpatokal/openflights#1087]
Hello, 
 I cannot add this airline - https://hisky.aero/ https://en.wikipedia.org/wiki/HiSky because the drop down menu for the country is stuck on ALL and it's not changing whatever I do.
![image](https://user-images.githubusercontent.com/104897468/166657392-c09c1533-3b42-4d4a-9a4c-d90f7b932000.png)
Could you please help?
Have a nice day,
Dan

**Comment by gerhardgirk** [comment]
Same issue here, trying to add Breeze which the system can't seem to identify but getting the same country error:
![image](https://user-images.githubusercontent.com/110411099/182187180-06be6160-fbe9-4a9f-bbf3-28c4148630bc.png)
![image](https://user-images.githubusercontent.com/110411099/182187202-9a70dcc9-fa53-4d4d-96d6-754801d51b67.png)

**Comment by jraynorlxx** [comment]
Tried to do the same as gerhardgirk did and received same error.

**Comment by Virreoh** [comment]
I have the same issue... Trying to add Norwegian Air Sweden.

**Comment by jpatokal** [comment]
This is finally fixed!  Although it may take a while to roll out a fix, since it's part of the PHP7 upgrade.

**Comment by gerhardgirk** [comment]
Perfect, this is working in the PHP7 upgrade version. Thanks
