### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by naturefund-falk** [jpatokal/openflights#1088]
At least the data directory is not updated since 2 years. But also on the website some new mayor airports are missing. So whats the status of the project.

**Comment by reedy** [comment]
Would also be curious too... https://github.com/jpatokal/openflights/issues/1085 and https://github.com/jpatokal/openflights/issues/1083 make it somewhat hard to even attempt to hack on this codebase

**Comment by jpatokal** [comment]
'e's not dead but 'e's definitely pining for the fjords.  The airport and airline databases are so badly out of date that this requires a thorough cleanup, not just point fixes, and merging existing data with new data without breaking everybody's flights in the process has proven to be very complicated -- and I want to make this a clean process going forward, so the data can be updated going forward as well.  Realistically I don't expect to be able to finish this before 2023.

**Comment by reedy** [comment]
What's the best way to make/contribute patches that are likely to be merged?

It'd be great to do some automated cleanup of code style... Fixing things like leading whitespace, consistent use of `{}` around conditionals (see openssl for the issues not using them can cause), and other cleanup of some legacy code and practices... For example most of the trailing `?>` are not needed, and generally are actively advised against being done...

**Comment by jpatokal** [comment]
I'm happy to review any reasonable-looking pull requests.

**Comment by chrisrosset** [comment]
I would be interested in helping out with code improvement efforts. I've managed to get the site running locally because I think I'm affected by #1101 (not much progress there just yet).

Are there specific small things worth looking at? Cleaning up errors, upgrading to PHP8, or something else entirely?

@reedy, I see you've been sending lots of PRs lately. Are you working towards something specific?

**Comment by reedy** [comment]
> @reedy, I see you've been sending lots of PRs lately. Are you working towards something specific?

Not really; fixing a mixture of bugs (that affect me, at least) and trying to improve things generally.

Some of the PR are fixing deprecated related logspam, in which some cases will be more an issue in PHP 8.0/8.1/8.2 with things becoming more strict.

**Comment by reedy** [comment]
It's a question for @jpatokal I guess... Whether there's a chance of more people getting rights to merge code, and to some extent deploy it...
