### ISSUE TITLE
Unable to upload csv file

### ISSUE THREAD

**Issue by wshaw17** [jpatokal/openflights#1089]
It started week of June 1st, but unable to upload csv file with historical checked. It gives upload failure message.

**Comment by Adam-C-Smith** [comment]
I'm unable to upload any CSVs with flights at the moment. Checking or not checking the keep historical airline names box doesn't have any impact. Just an error every time. Happens in both Chrome and Edge. Was working fine until a couple weeks ago, as I uploaded some flights on October 12 or 13.

**Comment by chadvincente** [comment]
I'm also having the same issue. I even tried exporting a file from OpenFlights, and then re-importing the same file, but that doesn't work either.

**Comment by jpatokal** [comment]
This was a permissions issue on the new server that should be fixed now, please try again.
