### ISSUE TITLE
No Flight Routes from/to BLB

### ISSUE THREAD

**Issue by flukmanji** [jpatokal/openflights#1093]
There aren't any flight routes  showing from/to BLB in openflights.org

**Comment by Floriaantasche** [comment]
There used to be regular flights in 2016/2017. Not sure what current status is. Looks like that location of BLB has been updated. So original request can be closed.

**Comment by flukmanji** [comment]
Hi, so I myself have added those routes currently showing for BLB airport under openflights, and these are all recent flights flown…wondering how they are not showing in openflights?

Farida

**Comment by reedy** [comment]
The routes database is something completely different... Not from user entered flights.

Dupe of #637
