### ISSUE TITLE
Upgrade to Nginx/PHP7/Ubuntu 22 LTS

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#1096]
The OpenFlights backend is falling apart, so I've embarked on an emergency upgrade to bring it kicking and screaming into the 2010s.   Please kick the tires at http://nginx.openflights.org/.  Beware: this uses the live prod database!

Seems to be working:
- Basic viewing and editing
- Airline, airport searches
- TripIt imports
- Secondary UIs (/user/X, /trip/X, etc)

Known bugs:
- None?

**Comment by 2sylbl** [comment]
Seems to be faster now, FWIW.

**Comment by jpatokal** [comment]
Good to hear!  Will do some more testing tomorrow, but if all goes well I expect to launch this by the end of the week.

**Comment by gerhardgirk** [comment]
this works well for me and agree it seems faster as well

**Comment by jpatokal** [comment]
https://openflights.org is now being served by the new server.

**Comment by reedy** [comment]
![image](https://user-images.githubusercontent.com/67615/196015891-f6b91049-74d7-41de-93b5-868c17ea594a.png)

`jpatokal@openflights-web:~/openflights$ cat html/ad.html` is showing on the homepage

**Comment by jpatokal** [comment]
Whoops!  @reedy Should be sorted out now, thank you.

**Comment by reedy** [comment]
https://openflights.org/about - Site statistics is giving a 404

<img width="1083" alt="Screenshot 2022-10-18 at 22 11 55" src="https://user-images.githubusercontent.com/67615/196545874-4072bf26-2203-4dfb-b6af-099f803ac944.png">

**Comment by reedy** [comment]
https://openflights.org/php/flights.php?export=backup gives a CloudFlare 502 error

Same for https://openflights.org/php/flights.php?user=0&trid=0&alid=0&year=0&param=MAP&id=0&export=gcmap and https://openflights.org/php/flights.php?user=0&trid=0&alid=0&year=0&param=MAP&id=0&export=export too

**Comment by reedy** [comment]
<img width="1279" alt="Screenshot 2022-12-02 at 01 33 15" src="https://user-images.githubusercontent.com/67615/205194569-fb1c809e-cf84-4487-a4ae-a46e94c6bce4.png">

The js files are indeed a 404...

**Comment by reedy** [comment]
https://openflights.org/theme/default/style.css too is further down...

**Comment by jpatokal** [comment]
The JS/CSS errors are not new but they're also not significant, I think those are coming from Prototype.js or something trying to find components not actually used by OpenFlights.

I'm going to close out this bug and follow up in the individually referenced bugs.

**Comment by reedy** [comment]
> https://openflights.org/about - Site statistics is giving a 404
> 
> 
> 
> <img width="1083" alt="Screenshot 2022-10-18 at 22 11 55" src="https://user-images.githubusercontent.com/67615/196545874-4072bf26-2203-4dfb-b6af-099f803ac944.png">
> 
> 

^ is still broken but not filed in a separate bug
