### ISSUE TITLE
[Bug] Distance showing in wrong format

### ISSUE THREAD

**Issue by sww326** [jpatokal/openflights#1111]
My settings are set to display distances in miles, but they nonetheless appear in km on my main account dashboard. 

![Screenshot 2022-10-29 163348-1](https://user-images.githubusercontent.com/93016834/198856376-69de73d5-19cd-47b5-93f4-9f02b72b2994.png)
![Screenshot 2022-10-29 163427-2](https://user-images.githubusercontent.com/93016834/198856392-cfbf22c0-21b0-4a66-ad5b-09e1192923f0.png)

(I'm not a coder, so apologies if I've entered this incorrectly.)

**Comment by andreiz** [comment]
Can confirm happening here as well

**Comment by drewguy** [comment]
Same (and whoops already submitted separate bug report (#1118)

**Comment by jpatokal** [comment]
Found and fixed: turns out `==` evaluates before `??` in PHP, so`X ?? null == "K"` was always evaluating as true!
