### ISSUE TITLE
Unable to Import Flights

### ISSUE THREAD

**Issue by seabambam** [jpatokal/openflights#1116]
I'm trying to import flights into my flightmemory from a CSV and the process seems to be stalling at the screen shown. I've tried both Chrome and Edge to no success
![image](https://user-images.githubusercontent.com/118080871/201495042-e4863387-0598-4b22-95b4-9f6ccec473e0.png)

**Comment by Wnt2Fly** [comment]
same here.. no matter what I try the system will not import; really frustrating.. any fix coming?

**Comment by reedy** [comment]
Likely fallout from https://github.com/jpatokal/openflights/issues/1096

**Comment by jpatokal** [comment]
Thanks for the bug report: looks like `ereg` no longer works in PHP7, upgraded to `preg_match` and I was able to import your file.  This may also explain a few other mysterious post-upgrade bugs .
