### ISSUE TITLE
CSV Export not working

### ISSUE THREAD

**Issue by drewguy** [jpatokal/openflights#1119]
CSV export from flights list page results in error reported by Cloudflare from openflights.

Works from settings page

**Comment by reedy** [comment]
Mentioned in https://github.com/jpatokal/openflights/issues/1096#issuecomment-1283013312

**Comment by jpatokal** [comment]
Unfortunately I'm unable to replicate, CSV exports from the flights page are working fine for me.  I'm particularly mystified that it's working from Settings, since the data is obviously identical and they're calling the same backend to export.

**Comment by reedy** [comment]
FWIW, neither work for me

https://openflights.org/php/flights.php?user=0&trid=0&alid=0&year=0&param=MAP&id=0&export=export

and

https://openflights.org/php/flights.php?export=backup

Both give "The web server reported a bad gateway error."

What do the error logs tell you? I'm getting it's a PHP fatal/similar...

**Comment by reedy** [comment]
When I can get a local working dev install, I might be able to help a bit more ;)

**Comment by reedy** [comment]
@drewguy Do you know how big your CSV backups have been previously?

**Comment by drewguy** [comment]
Showing 457kb when I was able to do it using the other link . . . (I have about 500 flights with just flight data not extensive notes)

**Comment by drewguy** [comment]
It's not getting the error now so I'll close . . . may have been temporary glitch

**Comment by reedy** [comment]
It's still broken for me - https://openflights.org/php/flights.php?export=backup

Mines only ~60KB with over 500 flights in it

**Comment by stillinbeta** [comment]
Broken for me as well, with 205 flights:

```
document.getElementById('apttable').select('tr').length
205 
```

**Comment by reedy** [comment]
I've posted a fix that seems to work locally... Just needs review, merge, deployment and further testing :)
