### ISSUE TITLE
Flights not ordered by UTC time

### ISSUE THREAD

**Issue by ssegraves** [jpatokal/openflights#1160]
When listing flights, the flights are ordered by the entered time, not the UTC version of that time. 

For example, flying NRT-SEA on January 3, leaving NRT at 5p and arriving SEA at 9am and then flying on Jan 3 SEA-PDX leaving SEA at 1p and arriving PDX at 1:30p, the NRT-SEA flight will be at the top of the listed flights.

**Comment by chrisrosset** [comment]
This is a duplicate of https://github.com/jpatokal/openflights/issues/24.

**Comment by ssegraves** [comment]
Going ahead and closing it based on @chrisrosset pointing out that it is a duplicate.
