### ISSUE TITLE
Can't export to CSV

### ISSUE THREAD

**Issue by gerhardgirk** [jpatokal/openflights#1164]
Cloudflare error when trying to export to CSV. Tried on multiple browsers and networks with the same result...
![image](https://user-images.githubusercontent.com/110411099/211035555-e93ed464-0d03-4f72-abe5-4b67da9980fa.png)

**Comment by reedy** [comment]
Dupe of https://github.com/jpatokal/openflights/issues/1119

Fix is in https://github.com/jpatokal/openflights/pull/1150

**Comment by jpatokal** [comment]
Apologies for the massive delay, the fix has been merged and deployed.  Any better now?

**Comment by gerhardgirk** [comment]
Works now, thanks a lot.
