### ISSUE TITLE
Can't access user profile - problem with period in name?

### ISSUE THREAD

**Issue by Adam-C-Smith** [jpatokal/openflights#1167]
My OpenFlights user name is adam.smith. I'm pretty sure it used to be possible for people to access my profile using the standard URL of https://openflights.org/user/adam.smith. But it has recently been throwing up a 404 Not Found error. I'm wondering whether some recent change has create a problem with the period in the name?

**Comment by reedy** [comment]
There was a swap in webserver (Apache to Nginx); I wouldn't be surprised if this is "just" an encoding issue from the upgrade in https://github.com/jpatokal/openflights/issues/1096

Will add it to my todo list

**Comment by reedy** [comment]
Confirmed fixed
