### ISSUE TITLE
Update airport Fort William (FTW/)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#1173]
New airport edit suggestion submitted by SeattleFlyerGuy:

Array
(
    [apid] => 
    [name] => Fort William
    [city] => Fort William
    [country] => United Kingdom
    [iata] => FTW
    [icao] => 
    [x] => -5.106139897108003
    [y] => 56.820428367252006
    [elevation] => 5
    [timezone] => 0
    [dst] => U
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Fort Worth Meacham International Airport
    [city] => Fort Worth
    [country] => United States
    [country_code] => 
    [iata] => FTW
    [icao] => KFTW
    [x] => -97.362396
    [y] => 32.819801
    [elevation] => 710
    [apid] => 3723
    [uid] => 
    [timezone] => -6
    [dst] => A
    [tz_id] => America/Chicago
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by chrisrosset** [comment]
This update is wrong - FTW remains "Fort Worth Meacham" according to multiple sources I checked.

@reedy, this can be closed.
