### ISSUE TITLE
The website is becoming less and less usable over time.

### ISSUE THREAD

**Issue by wangchun** [jpatokal/openflights#1175]
About 50% of the chance when I click "List flights", it stuck at loading. And about some 25% chance, when I export CSV, only first part of the flights is exported with the rest trimmed and missing. So annoying.

I have 600+ records, is that the reason? My openflights username same as my github’s. I am happy to make a donation if this project is having challenges to scale.

**Comment by wangchun** [comment]
I inspected the network request, only the first 539 lines is loaded and the connection is dropped. It is why "List flights" takes forever.

**Comment by 2sylbl** [comment]
@wangchun see issue 1101: https://github.com/jpatokal/openflights/issues/1101 

I have found that you can get a full CSV backup from the settings page despite this issue.

**Comment by reedy** [comment]
Export seems to be broken with a large enough list of files, so I'm slightly surprised you get a partial file.

I've filed https://github.com/jpatokal/openflights/pull/1150 to fix https://github.com/jpatokal/openflights/issues/1119 but it needs reviewing/merging and deploying...

**Comment by jpatokal** [comment]
Apologies for the massive delay, the fix has been merged and deployed.  Any better now?

**Comment by jpatokal** [comment]
Based on the comments in #1119 this should be fixed, so closing this as well.
