### ISSUE TITLE
Create a SECURITY.md

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1187]
As per https://github.com/jpatokal/openflights/issues/1056

https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by reedy** [comment]
@jpatokal probably want to decide how/where we want these reporting

**Comment by reedy** [comment]
https://openflights.org/about

>To get in touch with the team behind OpenFlights, send mail to info at openflights dot org or info at contentshare dot sg.

Is that good enough?

**Comment by psmoros** [comment]
Hey @reedy ! That's good enough for us (i'm with huntr.dev). The report is private in order to ensure responsible disclosure but we will send it to you via the provided email. Thank you  :))
