### ISSUE TITLE
Ability to set custom distance

### ISSUE THREAD

**Issue by matthew-dyson** [jpatokal/openflights#1203]
It'd be handy to be able to set a custom distance, especially in instances of a flight that takes off and lands at the same destination (for example sightseeing, training, or disrupted operations). This will ensure, even a 3-hour flight to nowhere, will still contribute to the overall distance travelled of a user.

**Comment by chrisrosset** [comment]
I believe this is already possible. I have one such flight (disrupted operations, had to turn back halfway through).

![custom-distance](https://github.com/jpatokal/openflights/assets/1103294/eb07cc04-b46d-4c83-b3f7-9a07091d99d1)

Changing the distance will only update the total distance after refreshing the page though.

**Comment by matthew-dyson** [comment]
How'd you get this distance into OpenFlights? I've not got an option online to add a manual distance, but I _think_ I could through a CSV import.

**List view:**
<img width="1383" alt="Screenshot 2023-06-18 at 14 08 48" src="https://github.com/jpatokal/openflights/assets/102329447/a5e0604a-9b88-43e8-984a-763967c3fb5f">

**Detailed edit view:**
<img width="909" alt="Screenshot 2023-06-18 at 14 09 47" src="https://github.com/jpatokal/openflights/assets/102329447/846473dd-4807-4f7b-bd38-c7c29d16e230">

**Comment by chrisrosset** [comment]
I did it by editing the input boxes that show up on the lower right hand
side of the map (duration and distance) and the clicking Save.

**Comment by matthew-dyson** [comment]
Actual magic. I don't think I would've seen that in a thousand years *facepalm*.

Closing!
