### ISSUE TITLE
[Bug] Convert airline, airport data to UTF8 [sf#122]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#122]
**Reported by jpatokal on 2012-01-15 10:20 UTC**
Airline and airport data is stored as Latin-1, but CSV exports are UTF-8, which obviously causes problems.   Everything should be converted to UTF-8 instead.

**Comment by chrisrosset** [comment]
I think this was kind of done. We use MySQL's `CHARSET=utf8` which, of course, does not actually support UTF-8.
