### ISSUE TITLE
List flights not working for certain airports

### ISSUE THREAD

**Issue by Adam-C-Smith** [jpatokal/openflights#1220]
For some reason, for at least a few weeks, I've been unable to list flights for certain airports. For instance, ORD and YYT both do nothing when I try to list flights. The spinning plane doesn't appear, it doesn't give me a blank list, it just doesn't change anything. I'm not sure whether this is a problem with these airports (i.e. do others have the same problem with these airports), or something specific in my list of flights?

I clicked around a whole bunch of different airports that I've flown to today and also found NCE has the same issue. No common factors between these airports or my flights involving them, as far as I can tell.

**Comment by chrisrosset** [comment]
Took a minute to investigate and this is the same issue as https://github.com/jpatokal/openflights/issues/781 reported in 2017.

This is a front-end bug.

The common factor between all of these is that they have a quote in the full name which [isn't properly escaped between JS and HTML](https://github.com/jpatokal/openflights/blob/ecf635a4bc460a5ce3a911c34305672188ad6d80/openflights.js#L478).

- Chicago O'Hare Internation. (ORD), United States
- St. John's International Airport (YYT), Canada
- Nice-Côte d'Azur Airport (NCE), France
