### ISSUE TITLE
Proposal: remove widget code

### ISSUE THREAD

**Issue by chrisrosset** [jpatokal/openflights#1224]
@jpatokal, I would like to propose the removal of the map widget code.

The map widget hasn't seen any meaningful updates since it was first created in Feb 2010 (880b3f3b1b5ef396826aa72a224264f9397a23fe and 880b3f3b1b5ef396826aa72a224264f9397a23fe). I'm afraid it's beyond redemption - I doubt this code can be reasonably embedded into any modern website.

Removing this code would reduce the changes needed to support transitioning to JSON-based server APIs (which I've already started in #1222 with `top10.php`) and upgrading OpenLayers (ongoing discussion in #1192 with some work in progress). It would also allow us to remove `prototype.js` if the autocomplete upgrade (#1223) gets merged.

**Comment by jpatokal** [comment]
Belated comment: yes, this is fine, it's indeed long obsolete.
