### ISSUE TITLE
Make user ID for "demo mode" configurable

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1232]
Including Top 10 (logged out) usage etc

Forked from #1225

**Comment by chrisrosset** [comment]
While we're here, I just wanted to point out another "special" User ID [defined in `config.php`](https://github.com/jpatokal/openflights/blob/52e054d87d63ba0d43153ff61ef8ed59b8fb0d3a/php/config.php.sample#L20).

I think it would be a good idea to define a similar constant to the demo ID and replace the hardcoded `1`s.

**Comment by reedy** [comment]
I note `$OF_ADMIN_UID` isn't actually a constant, just a variable named like it could/should be one ;)

**Comment by reedy** [comment]
> I note `$OF_ADMIN_UID` isn't actually a constant, just a variable named like it could/should be one ;)

And possibly, it should become an array too...

Doesn't seem unreasonable there'd be more than 1 "admin" account

**Comment by chrisrosset** [comment]
> > I note `$OF_ADMIN_UID` isn't actually a constant, just a variable named like it could/should be one ;)
> 
> And possibly, it should become an array too...
> 
> Doesn't seem unreasonable there'd be more than 1 "admin" account

You're not wrong but I think it's unlikely there will be more than one. :)
