### ISSUE TITLE
Airline and Airport search windows regression

### ISSUE THREAD

**Issue by chrisrosset** [jpatokal/openflights#1240]
The airline search popup (`html/alsearch`) no longer loads any results.

Something goes wrong when querying for the airline counts:

```
Undefined variable: max in /var/www/openflights/php/alsearch.php on line 228
```

Because the value is never sent, the UI thinks there are no results.

@reedy, the behavior changed with b4ebe4763e57785cdfdda0a0a7ccc3aebf08679a.

**Comment by chrisrosset** [comment]
This also affects the airport search window.

**Comment by reedy** [comment]
That should fix at least one of them...

**Comment by reedy** [comment]
What's the error on apsearch?

**Comment by chrisrosset** [comment]
It's the same thing:

```
Undefined variable: max in /var/www/openflights/php/apsearch.php on line 247
```

I think you flipped the `$row` condition there too by accident.

**Comment by reedy** [comment]
That's in 04d330ad04de9e574180eefc87016925c7fa466c

I guess that explains it, as I was looking at the diff for the other commit

**Comment by chrisrosset** [comment]
Fixed now.

**Comment by reedy** [comment]
Cheers!
