### ISSUE TITLE
"XML Parsing Error: not well-formed" when using Carrier autocomplete

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1272]
For some reason, typing in `b` or `B` results into the Carrier box when adding a new flight results in

```
XML Parsing Error: not well-formed
Location: https://openflights/
Line Number 1, Column 64:
```

**Comment by reedy** [comment]
![Screenshot 2023-07-11 at 00 05 25](https://github.com/jpatokal/openflights/assets/67615/15b3cdf7-8c0d-40bd-831c-be70564175af)

Guessing it's an encoding error related to `&`...

**Comment by chrisrosset** [comment]
Yeah, I found this while testing my JSON autocomplete changes which include
a fix. I need to wrap up these changes and send a PR.
