### ISSUE TITLE
Display user id on profile/settings

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1295]
Useful for debugging stuff...

**Comment by chrisrosset** [comment]
Is this really something that's worth displaying to the user? We display the name and that's just one SQL query away from the ID...

**Comment by reedy** [comment]
Only if you have database access...

**Comment by chrisrosset** [comment]
> Only if you have database access...

That's true but if you don't have it (and server access) what good does it do you?

**Comment by reedy** [comment]
Various of the PHP endpoints do accept GET/POST params for the UID, and then you can get the output... Can be useful for testing/verifying/comparing against the live site

**Comment by chrisrosset** [comment]
`login.php` sends back uid in the response (key "uid"). Could be useful if you need a live site login today.
