### ISSUE TITLE
airlines table missing frequency column

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1315]
https://github.com/jpatokal/openflights/blob/master/php/import.php#L167

**Comment by chrisrosset** [comment]
Relevant schema from the live DB here: https://github.com/jpatokal/openflights/issues/1137#issuecomment-1339376478

Some relevant conversation here: #1210

**Comment by reedy** [comment]
Looks like it's only `frequency` missing...

`clean-duplicate-airlines.sql` would add it, if you wanted to run it. Guess we should just add it to the base schema for ease though
