### ISSUE TITLE
GitHub search is too simplistic

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1318]
```
            $issues = $github->api('search')->issues("repo:$GITHUB_USER/$GITHUB_REPO is:issue in:title $identifier");

            if (count($issues['items']) > 0) {
                // Existing issue, add comment
                $issueNumber = $issues['items'][0]['number'];
                // https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment
                $result = $github->api('issue')->comments()->create(
                    $GITHUB_USER,
                    $GITHUB_REPO,
                    $issueNumber,
                    ['body' => $body]
                );
            } else {
                // New issue
                // https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue
                $result = $github->api('issue')->create(
                    $GITHUB_USER,
                    $GITHUB_REPO,
                    ['title' => $subject, 'body' => $body, 'labels' => ['airport']]
                );
                $issueNumber = $result['number'];
            }
```

This looks for any task with the identifier in the title... Which results in comments being left on unrelated tasks, like https://github.com/jpatokal/openflights/issues/499#issuecomment-203581482

**Comment by reedy** [comment]
I wonder if it should look for the specific titled tasks matching (exactly?) `sprintf("Update airport %s (%s/%s)", $airport, $iata, $icao)`?

**Comment by chrisrosset** [comment]
Related issue: https://github.com/jpatokal/openflights/issues/354

**Comment by reedy** [comment]
> I wonder if it should look for the specific titled tasks matching (exactly?) `sprintf("Update airport %s (%s/%s)", $airport, $iata, $icao)`?

Or searching for the `(%s/%s)` part at least... Arguably airport names may change more commonly than the name staying the same and the IATA/ICAO changing?

This seems better than the current behaviour which just picks the first issue with the ICAO (falling back to IATA if no ICAO) code in the subject...

If we did #354, it would probably mean changing the subject (causing some duplicates, maybe, if we did an exact search), and possibly the description, and do some sort of fallback search... Or we just look for the `(%s/%s)` and keep that common.

May not catch manually entered ones, but that seems fine.

**Comment by chrisrosset** [comment]
> > I wonder if it should look for the specific titled tasks matching (exactly?) `sprintf("Update airport %s (%s/%s)", $airport, $iata, $icao)`?
> 
> Or searching for the `(%s/%s)` part at least... Arguably airport names may change more commonly than the name staying the same and the IATA/ICAO changing?

Instead of searching by title alone, would it be possible to also filter on the "airport" issue label?

**Comment by reedy** [comment]
Yup, very trivially...
