### ISSUE TITLE
locale script broken again...

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1333]
Guessing it doesn't like PHP's short array syntax...

**Comment by reedy** [comment]
Nope, it's HEREDOC related...

**Comment by reedy** [comment]
It's definitely upset by https://github.com/jpatokal/openflights/commit/0f1adfcaae5d35ddb7337761da480d4fd34bec77

With that patch... It's still trying to remove a few messages...

```
-msgid "Longest"
-msgstr ""
-
-msgid "Shortest"
-msgstr ""
-
-msgid "Northernmost"
-msgstr ""
-
-msgid "Southernmost"
-msgstr ""
-
-msgid "Westernmost"
-msgstr ""
-
-msgid "Easternmost"
-msgstr ""
```

**Comment by reedy** [comment]
And if I take stats.php back to https://github.com/jpatokal/openflights/blob/968137cc25516a555d12a467a7cb1ab53e417b8f/php/stats.php it works fine... :/

**Comment by reedy** [comment]
https://github.com/jpatokal/openflights/commit/0f1adfcaae5d35ddb7337761da480d4fd34bec77#diff-0df56859af0f3003d81e2bb441c9363e7641714dbb641b54333527f6273f1eb8L88-R111

This change causes problems...

**Comment by reedy** [comment]
https://github.com/jpatokal/openflights/commit/0f1adfcaae5d35ddb7337761da480d4fd34bec77#diff-0df56859af0f3003d81e2bb441c9363e7641714dbb641b54333527f6273f1eb8R138-R183 too

**Comment by reedy** [comment]
Ok, I think it's related to HEREDOC inside function calls (`sprintf`)... Lets try

**Comment by reedy** [comment]
@chrisrosset FYI...

Two takeaways from this...

If you're using heredoc `<<<FOO` make sure the `FOO;` is unindented.

Don't chain it into a `sprintf()` ccall, such as `sprintf(<<<FOO`, just stick it to a variable...

Stupid bugs.

**Comment by chrisrosset** [comment]
> @chrisrosset FYI...
> 
> Two takeaways from this...
> 
> If you're using heredoc `<<<FOO` make sure the `FOO;` is unindented.
> 
> Don't chain it into a `sprintf()` ccall, such as `sprintf(<<<FOO`, just stick it to a variable...
> 
> Stupid bugs.

Some of this is a bit self-inflicted because we do localization in the weirdest places (like embedding a localized string as constants into SQL queries so we can get them back and then send to the UI...).
