### ISSUE TITLE
Number formatting on Top 10/Analyse

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1344]
It would be nice if the numbers had some thousands seperators...

And when sorting by mileage on Top 10, add the units after the distance as atm it's completely uncler which unit it is using...

**Comment by reedy** [comment]
#1296 would be helpful...

**Comment by chrisrosset** [comment]
Displaying the unit suffix was first requested in https://github.com/jpatokal/openflights/issues/291 so maybe it should be merged into this ticket?
