### ISSUE TITLE
Remove vbulletin "integration"?

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1355]
map.php has:

```
// Login via vBulletin cookies
$bb_uid = $_COOKIE["bb_userid"] ?? null;
if ($OF_VBULLETIN_LOGIN && ! empty($bb_uid)) {
    $sth = $dbh->prepare("SELECT uid, name, email, editor, elite, units, locale FROM users WHERE bb_uid = ?");
    $sth->execute([$bb_uid]);
    $row = $sth->fetch();
    if ($row) {
        $uid = $_SESSION['uid'] = $row["uid"];
        $_SESSION['name'] = $row["name"];
        $_SESSION['email'] = $row["email"];
        $_SESSION['editor'] = $row["editor"];
        $_SESSION['elite'] = $row["elite"];
        $_SESSION['units'] = $row["units"];
    } elseif (!$trid && !$user) {
        die("Signup;No username found for ID " . $bb_uid);
    }
}
```

I can't see any code path where the `users.bb_uid` can even be set...

And the `vbulletin=true` passed to `html/settings.php` in `openflights.js` doesn't seem to do anything.

Does this serve any value anymore @jpatokal ?

Was added in c7b2cdf3967c8471eeddf284a45a038aba64278d

**Comment by chrisrosset** [comment]
`users.bb_uid` is also missing from the DDL statements.

Is it possible that this was created for a couple specific FlyerTalk members and enabled through manual updates to the database? :)

**Comment by reedy** [comment]
> `users.bb_uid` is also missing from the DDL statements.

Yeah, that's how I spotted it!

**Comment by jpatokal** [comment]
This was originally added for the Australian Frequent Flyer website, which ran their own licensed fork of OpenFlights integrated with their vBulletin system.  However, [this was decommissioned in 2020](https://www.australianfrequentflyer.com.au/community/threads/flight-tracker-to-be-retired-your-action-may-be-required-new-aff-style.100194/), so the references to vBulletin are now obsolete and can be removed.
