### ISSUE TITLE
Layout regression in Detailed Flight Editor

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1372]
![Screenshot 2023-07-18 at 00 49 16](https://github.com/jpatokal/openflights/assets/67615/15c03fad-ebba-44f2-a25e-0c72ea3862fe)

If you revert the entire table change for that section, it fixes it...

So will be something trivial that I've upset in https://github.com/jpatokal/openflights/commit/ab0c8e47d4f8725d141873c285f6b7ed8ffa7cdb#diff-7413d6453f901e939bbd840c8f0d1c7b20c2ca0e7f71741e4e07c6cf036f16c0L197-L316

Feel free to pick up/fix

**Comment by reedy** [comment]
A missing `"`. Fix incoming

**Comment by chrisrosset** [comment]
Bisected down to ab0c8e47d4f8725d141873c285f6b7ed8ffa7cdb.

**Comment by chrisrosset** [comment]
Ah, saw the message over email missed the commit link. Leaving to you.
