### ISSUE TITLE
[Bug] Impossible to enter login/password in iPhone landscape mode [sf#140]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#140]
**Reported by vtual on 2012-08-14 09:22 UTC**
When on the iPhone's landscape mode it is impossible to select the login/password fields to login. In portrait mode is works perfectly.

**Comment by jpatokal** [comment]
**Commented by jpatokal on 2012-08-14 13:01 UTC**
The iPhone (or any mobile) is not a currently a supported platform for OpenFlights, so this will not be fixed in the foreseeable future.  There's a third-party Android app in the works, but that will not help you very much...

**Comment by jpatokal** [comment]
**Updated by jpatokal on 2012-08-14 13:01 UTC**
- **priority**: 5 --> 1

**Comment by reedy** [comment]
![image](https://github.com/jpatokal/openflights/assets/67615/f2c46620-ba1e-471d-9fff-9e7d8799f3e4)
