### ISSUE TITLE
Display issue for airport names

### ISSUE THREAD

**Issue by yibozeng** [jpatokal/openflights#1423]
Not sure if this is a bug, but not able to show asia and north america airports at the same time when looking across the pacific (see attached)
![Screenshot 2023-07-27 at 9 50 59 AM](https://github.com/jpatokal/openflights/assets/37231593/5e9b86eb-5d73-42c8-9d70-0670ed5928d2)
![Screenshot 2023-07-27 at 9 50 50 AM](https://github.com/jpatokal/openflights/assets/37231593/5e1b163e-a565-4678-a374-c56b03ab0d3a)

Thanks!

**Comment by chrisrosset** [comment]
#2

**Comment by chrisrosset** [comment]
It's the oldest issue we have. :)
