### ISSUE TITLE
Exclusivly Helicopters Flights

### ISSUE THREAD

**Issue by Mandinilla** [jpatokal/openflights#1433]
Hello! I'm looking for a screen shot of exclusivly helicopter flights that went through and, or, landed in the south east florida area spanning from Miami Dade to St. Lucie and Okeechobee county (going north) from today's date going back 4 years. 

Could you compile the data for me? 

It's REALLY important. Even if the aircraft is on private, can you still capture the data?

**Comment by chrisrosset** [comment]
Hi! This website only tracks flights as entered by its users. While some users choose to record their helicopter flights, this is not a very common use case. Even if we were to ignore the potential privacy concerns for a moment, the data is not readily available.

There are several commercial enterprises in this space which capture data for all flights in the United States. They would have extensive historical records and would be in a better position to fulfill your request.

**Comment by Mandinilla** [comment]
Hey!

Could you please let me know the commercial agencies that can provide me
with this that ignore privacy concerns?

Knowing him he's probably on the LAAD list or PIA

Also, see the article:

https://www.planeandpilotmag.com/article/privacy-lost-in-the-age-of-ads-b/

"One company in particular sends regular FOIA requests to the FAA in order
to sell competitive data to other companies. It simply asks the FAA
regularly for a list of all PIA addresses and who they belong to. Then it
sells elaborate reports telling companies exactly what ALL their
competitors’ aircraft are doing at all times. It may be legal, but let’s
just say that the ethics of this practice are questionable at best."

What are the names of the companies that are doing this?

Please let me know. All input is appreciated.

Amanda Ramirez

**Comment by Mandinilla** [comment]
Also, I appreciate your rapid response.

Amanda
