### ISSUE TITLE
Follow up on helicopters 

### ISSUE THREAD

**Issue by Mandinilla** [jpatokal/openflights#1434]
Hey! 

Could you please let me know the commercial agencies that can provide me with this that ignore privacy concerns?

Knowing him he's probably on the LAAD list or PIA

Also, see the article:

https://www.planeandpilotmag.com/article/privacy-lost-in-the-age-of-ads-b/

"One company in particular sends regular FOIA requests to the FAA in order to sell competitive data to other companies. It simply asks the FAA regularly for a list of all PIA addresses and who they belong to. Then it sells elaborate reports telling companies exactly what ALL their competitors’ aircraft are doing at all times. It may be legal, but let’s just say that the ethics of this practice are questionable at best."

What are the names of the companies that are doing this?

Please let me know. All input is appreciated.

Amanda Ramirez

**Comment by reedy** [comment]
Pretty sure this is off topic and out of scope...
