### ISSUE TITLE
Top 10 in km not working

### ISSUE THREAD

**Issue by strainu** [jpatokal/openflights#1441]
Login as an user with distance setting set to km. Go to Top 10, then select "Sort by...Mileage". Instead of the values, I get "[undefined](https://openflights.org/#)	NaN" in all columns.

**Comment by strainu** [comment]
@reedy any idea if 4bd086d48d8e098772fdbc16b47c3560fdaabd1c fixes this?

**Comment by reedy** [comment]
It should, yeah... It was broken by 09b36136e15bf31f1f4b10c98f2ab99b3e6980d6 which was deployed in late June, as per #1391
