### ISSUE TITLE
Importing from flightmemory does not work

### ISSUE THREAD

**Issue by zeitwesen** [jpatokal/openflights#1443]
Importing html from flightmemory.com is stuck on parsing.
Full import log:

```
OpenFlights: Import
Upload successful. Parsing...
Results
Tmpfile php35doLd
```

Would be cool if importing from flighmemory could be fixed again.

**Comment by reedy** [comment]
Probably fixed by the next deployment (#1391); I did quite a lot of testing/fixing - 1221682951056828a90eba660941ae548d9b8e29 among other commits
