### ISSUE TITLE
Issue 964 is recurring again

### ISSUE THREAD

**Issue by 2sylbl** [jpatokal/openflights#1446]
This issue is recurring again - autocomplete failing to show anything above a 737-500 if you use the correct hyphenation.

_Originally posted by @2sylbl in https://github.com/jpatokal/openflights/issues/964#issuecomment-1773975696_

**Comment by chrisrosset** [comment]
The back-end code still throws everything after a hyphen away when preparing the SQL query:
https://github.com/jpatokal/openflights/blob/f53e4522574e201796d5526b5f9e06e0ca506abb/php/autocomplete.php#L12-L16

**Comment by dnowacki** [comment]
+1, ran into this today
