### ISSUE TITLE
Unable to load homepage in Chrome and Safari

### ISSUE THREAD

**Issue by kennedyeric** [jpatokal/openflights#1448]
In both Chrome and Safari on a mac, I'm currently getting a popup window any time I've tried to access OpenFlights in the past 24hrs:

openflights.org says
(Error 404)
<html>
<head><title>404 Note Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by Gnopps** [comment]
I'm getting the same error on Firefox on android.

**Comment by jpatokal** [comment]
I've gotten several reports of this but am unable to replicate with Chrome on Linux or Android.

I suspect this has something to do with the locale handling changes, and I've deployed the changes below that should fix this.  Are you still seeing the issue?

https://github.com/jpatokal/openflights/issues/1391#issuecomment-1770695418

**Comment by kennedyeric** [comment]
It now seems to be working correctly - thank you!
