### ISSUE TITLE
Can't upload from FlightMemory

### ISSUE THREAD

**Issue by JamiesonB12** [jpatokal/openflights#1461]
Hi, I have not been able to upload flight data from FlightMemory HTML files when I tried today.

Here is the message I get:

Upload successful. Parsing...
Results
Tmpfile phpvYTcMw

Although it says 'successful', it is not uploading.

Would you be able to assist?

Thank you!

**Comment by Adam-C-Smith** [comment]
Same issue with uploading from a CSV file as well.

**Comment by reedy** [comment]
Something going on server side, the file seems to work fine locally

![Screenshot 2024-01-12 at 19 04 39](https://github.com/jpatokal/openflights/assets/67615/bca02e64-2964-4cc2-89da-7e17b797866f)

**Comment by reedy** [comment]
Do you have any `EconomyPlus` flights in your list?

I think from the fm.html I have saved here, you do...

Which can result in some PHP warnings:

```
PHP message: PHP Warning:  Undefined array key "EconomyPlus" in /var/www/openflights/php/import.php on line 807; PHP message: PHP Warning:  Undefined array key "EconomyPlus" in /var/www/openflights/php/import.php on line 807" while reading response header from upstream,
```

Should it be mapped to Economy or Premium Economy?

>Economy plus is a slightly upgraded economy experience, while premium economy is its own cabin with elevated service on international flights.

**Comment by Adam-C-Smith** [comment]
I'm not sure whether that question is directed at me or at @JamiesonB12 . I found that while I was unsuccessful at uploading a file several times on the day I reported the issue, it worked fine the next day, and I've subsequently uploaded other CSV files without problems. The EconomyPlus issue would not apply to me though.

**Comment by JamiesonB12** [comment]
> Do you have any `EconomyPlus` flights in your list?
> 
> I think from the fm.html I have saved here, you do...
> 
> Which can result in some PHP warnings:
> 
> ```
> PHP message: PHP Warning:  Undefined array key "EconomyPlus" in /var/www/openflights/php/import.php on line 807; PHP message: PHP Warning:  Undefined array key "EconomyPlus" in /var/www/openflights/php/import.php on line 807" while reading response header from upstream,
> ```
> 
> Should it be mapped to Economy or Premium Economy?
> 
> > Economy plus is a slightly upgraded economy experience, while premium economy is its own cabin with elevated service on international flights.

Thanks @reedy it should be mapped to Premium Economy. If that's the issue I can adjust the entries on Flight Memory to Economy (there are not a lot) to avoid the warnings.

**Comment by JamiesonB12** [comment]
I have just changed my Economy Plus flights to Business and tried to upload again. Still not working. Below is the message I got:

Upload successful. Parsing...
Results
Tmpfile phpghXCHS

**Comment by reedy** [comment]
There's two issues here, I think.

One is the lack of mapping, which is trivially enough fixed... And wouldn't probably stop the upload (as seen by it working locally)...

Second is whatever the openflights.org server is doing, but I don't have access, so can't check the logs etc to see

**Comment by IADflyer** [comment]
Same issue

**Comment by heybrian** [comment]
I've been getting the Tmpfile issue for over a year now. I have not been able to upload from FlightMemory since Feb 2023. I've tried everything, from simplifying my data, doing only one row at a time, trying the CSV file, etc. Is there any fix for this? Has anyone been able to upload the HTML from FlightMemory scrape?

**Comment by reedy** [comment]
If you can provide a copy of the file, I can try and test it. Otherwise it's just guess work :)
