### ISSUE TITLE
Parsing error when importing from CSV

### ISSUE THREAD

**Issue by franporta** [jpatokal/openflights#1462]
Importing from CSV leads to a serious parsing error: a sequence column is added as first one and all the others are shifted to the right.
The result is that every data is in the wrong plance.

I tried also re-importing a CSV export to be sure of the format but the error remains.

Once I accidentaly clicked to finalize the import: 3 record were addrd to the total of my flight but those are not visible anywhere, not even exporting.

**Comment by reedy** [comment]
![Screenshot 2024-01-12 at 18 42 05](https://github.com/jpatokal/openflights/assets/67615/e04ce26a-d3ec-4953-95f3-c278bed3843e)

**Comment by reedy** [comment]
> The result is that every data is in the wrong plance.

This seems to be only while it's being displayed before clicking upload. Actually importing it seems to work fine.
