### ISSUE TITLE
Can't import HTML screen scrape data from FlightMemory

### ISSUE THREAD

**Issue by Muflyer23** [jpatokal/openflights#1476]
I am attempting to convert my flight data from Flightmemory.com to Openflights.org and am using the screen scrape approach which generates HTML files. In trying to upload the files I get the response "Upload failed," but no more specific information.  Can you provide any assistance.  Thanks!

**Comment by reedy** [comment]
Can you provide the file?

**Comment by reedy** [comment]
Maybe a dupe of #1461

**Comment by littlev0ices** [comment]
I am having a similar challenge, in both cases there are no issues, the upload just freezes
File 1:  Nothing mention as wrong
File 2: Has economy plus -> Changed it to business manually.. zilch improvement

Example fail
`Import
Upload successful. Parsing...
Results
Tmpfile phpfeZVgI`
[FlightMemory - FlightData.zip](https://github.com/user-attachments/files/17005301/FlightMemory.-.FlightData.zip)

**Comment by reedy** [comment]
I'm able to import both of those successfully in to my local test/dev instance (I note that they're not very big files, either)

```
Importing...
Tmpfile php3SJgLz
71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22
Flights successfully imported.
```

```
Importing...
Tmpfile php6YDtDY
21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1
Flights successfully imported.
```

As per

>Second is whatever the openflights.org server is doing, but I don't have access, so can't check the logs etc to see

_Originally posted by @reedy in https://github.com/jpatokal/openflights/issues/1461#issuecomment-1919307615_

Would need some input from @jpatokal...

I can provide you a openflights export of those, if you need/want though.


Actually...

> Example fail `Import Upload successful. Parsing... Results Tmpfile phpfeZVgI` [FlightMemory - FlightData.zip](https://github.com/user-attachments/files/17005301/FlightMemory.-.FlightData.zip)

If you look at the HTML source of the popup window, does it have anything in it at all?

![Screenshot 2024-09-16 at 19 42 37](https://github.com/user-attachments/assets/cef38c84-69d6-420e-a072-5cff0d345904)

Or does it literally just seem to die at that point?

**Comment by reedy** [comment]
I love remembering I can answer my own questions/test things...

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>OpenFlights: Import</title>
<link rel="stylesheet" href="[/css/style_reset.min.css](view-source:https://openflights.org/css/style_reset.min.css)" type="text/css">
<link rel="stylesheet" href="[/openflights.css](view-source:https://openflights.org/openflights.css)" type="text/css">
<script type="text/javascript" src="[/js/Gettext.min.js](view-source:https://openflights.org/js/Gettext.min.js)"></script>
<script type="text/javascript" src="[/js/apsearch.js](view-source:https://openflights.org/js/apsearch.js)"></script>
</head>
<body>
<div id="contexthelp">
<h1>Import</h1>
<b>Upload successful. Parsing...</b><br><h4>Results</h4>Tmpfile <tt>phpt5YmC5</tt><br>
```

I bet I know what it is...

**Comment by littlev0ices** [comment]
Thanks for the cryptic comments :P: 

If you wouldn't mind uploading it here, then yes I would appreciate an openflights version of the file, as then hopefully I can upload that one

And to confirm with the HTML/web page - yes, it just freezes, nothing more happens, (I left it for varying lengths of time), and the account (which is brand new) never has any flights shown.

**Comment by reedy** [comment]
[openflights-backup-2024-09-16-1840.csv](https://github.com/user-attachments/files/17021552/openflights-backup-2024-09-16-1840.csv)

^ Do double check airlines/airports/models incase my dev instance has funky IDs that do something weird.

If my hunch is right... Basically, composer wasn't run (to properly update the vendor folder) after 36da5e2e5d1e3d6c0e3311920f22d4076b02668e was deployed.

As the `vendor/autoload.php` will exist, but I'm betting the needed class from `rubobaquero/phpquery` then doesn't exist, and it just fatals (with no error messages being shown due to debug/logging settings)

**Comment by jpatokal** [comment]
composer updated in prod, please try again.

```
  [...clearing old versions...]
  - Installing php-http/discovery (1.19.4): Cloning 0700efda8d from cache
  - Installing guzzlehttp/promises (2.0.3): Cloning 6ea8dd0886 from cache
  - Installing symfony/polyfill-php80 (v1.31.0): Cloning 60328e362d from cache
  - Installing symfony/deprecation-contracts (v2.5.3): Cloning 80d075412b from cache
  - Installing psr/http-message (2.0): Cloning 402d35bcb9 from cache
  - Installing ralouphie/getallheaders (3.0.3): Cloning 120b605dfe from cache
  - Installing psr/http-factory (1.1.0): Cloning 2b4765fddf from cache
  - Installing guzzlehttp/psr7 (2.7.0): Cloning a70f5c95fb from cache
  - Installing http-interop/http-factory-guzzle (1.2.0): Cloning 8f06e92b95 from cache
  - Installing psr/http-client (1.0.3): Cloning bb5906edc1 from cache
  - Installing guzzlehttp/guzzle (7.9.2): Cloning d281ed313b from cache
  - Installing psr/cache (1.0.1): Cloning d11b50ad22 from cache
  - Installing php-http/multipart-stream-builder (1.4.2): Cloning 10086e6de6 from cache
  - Installing php-http/promise (1.3.1): Cloning fc85b1fba3 from cache
  - Installing php-http/httplug (2.4.1): Cloning 5cad731844 from cache
  - Installing symfony/polyfill-php73 (v1.31.0): Cloning 0f68c03565 from cache
  - Installing symfony/options-resolver (v5.4.40): Cloning bd1afbde66 from cache
  - Installing clue/stream-filter (v1.7.0): Cloning 049509fef8 from cache
  - Installing php-http/message (1.16.1): Cloning 5997f32893 from cache
  - Installing php-http/client-common (2.7.2): Cloning 0cfe9858ab from cache
  - Installing php-http/cache-plugin (2.0.0): Cloning 539b2d1ea0 from cache
  - Upgrading knplabs/github-api (1.7.1 => v3.15.0): Checking out d4b7a1c00e from cache
  - Installing rubobaquero/phpquery (0.9.15): Cloning d2c3c1bb8a from cache
```

**Comment by littlev0ices** [comment]
Thanks @jpatokal  and @reedy , can confirm that my issue is now resolved and I was able to upload the files correctly, without even needing to change Premium Economy to a different class :)

**Comment by reedy** [comment]
2d76df96c935af598aa56b3437017a732bc20ac4 would've taken care of the other issue :)

**Comment by pepZRH** [comment]
[FlightMemory - FlightData_BIQ.zip](https://github.com/user-attachments/files/19552362/FlightMemory.-.FlightData_BIQ.zip)

Having the same issue.

<img width="180" alt="Image" src="https://github.com/user-attachments/assets/95172306-13a1-4fa6-b916-3e6ed41c1aa1" />

I've tried several .html files. First step is fine (Parsing completed successfully) but then it gets stuck in "Import"

**Comment by reedy** [comment]
It's probably a different issue...

**Comment by reedy** [comment]
> [FlightMemory - FlightData_BIQ.zip](https://github.com/user-attachments/files/19552362/FlightMemory.-.FlightData_BIQ.zip)
> 
> Having the same issue.
> <img alt="Image" width="180" src="https://private-user-images.githubusercontent.com/205789523/429058817-95172306-13a1-4fa6-b916-3e6ed41c1aa1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM1NDM1NjcsIm5iZiI6MTc0MzU0MzI2NywicGF0aCI6Ii8yMDU3ODk1MjMvNDI5MDU4ODE3LTk1MTcyMzA2LTEzYTEtNGZhNi1iOTE2LTNlNmVkNDFjMWFhMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwMVQyMTM0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTQxYTRkN2ZjYWMzYzY1M2U0OTQ0MTdiMDAxN2E2YTY0ZjI3ZGFlOTVhNTU3ZGE3MmJlZjMyZjhiNGQ1YWI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.R1HqiwcVUeipNo21yegdkogrX0CA59qqaP2OC7nzQ-k">
> 
> I've tried several .html files. First step is fine (Parsing completed successfully) but then it gets stuck in "Import"

![Image](https://github.com/user-attachments/assets/5567915b-f5dd-43c9-8423-c125b855336f)

```
2025/04/01 21:34:16 [error] 781#781: *21 FastCGI sent in stderr: "PHP message: PHP Warning:  PDOStatement::execute(): SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect time value: '06:50 pm' for column `flightdb2`.`flights`.`src_time` at row 1 in /var/www/openflights/php/import.php on line 816" while reading response header from upstream, client: 10.13.37.49, server: 10.13.37.36, request: "POST /php/import.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "10.13.37.36", referrer: "https://10.13.37.36/php/import.php"
```

**Comment by reedy** [comment]
If you remove the PM, it should import fine...

Obviously you shouldn't necessarily have to, but...

**Comment by reedy** [comment]
![Image](https://github.com/user-attachments/assets/d13a0948-8603-4426-ad2a-f3c22570e4ce)

It looks like FM wants it on 24H anyway... So why is it letting you save it?

**Comment by pepZRH** [comment]
FM forces into AM/PM automatically ;(

**Comment by reedy** [comment]
Is that new?

Other peoples imports haven't failed from it...

(I'll have to check some of the other linked files on here)

**Comment by pepZRH** [comment]
No idea, I've been using it since 2009 and it has been always been the case. Entering 24h format and FM forcing it into AM/PM

**Comment by reedy** [comment]
> [FlightMemory - FlightData.zip](https://github.com/user-attachments/files/17005301/FlightMemory.-.FlightData.zip)

If I grab this from @littlev0ices...

I don't see any AM/PM

![Image](https://github.com/user-attachments/assets/5e36278f-ffdb-4bc3-8e7c-ed04f37c0822)

On yours, there definitely is...

![Image](https://github.com/user-attachments/assets/7dc14dd3-3000-44d3-8e15-3ca55fad084c)

But does show a date formatting difference...

If we look at profile settings

![Image](https://github.com/user-attachments/assets/0aef62bf-c1c0-41b4-b46a-edcc4d2480ba)

**Comment by pepZRH** [comment]
You were absolutely right! Thanks a million @reedy!
