### ISSUE TITLE
[Bug] Unable to import data from TripIt. [sf#152]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#152]
**Reported by *anonymous on 2013-03-26 11:01 UTC**
When trying, the following message appears:
"Could not connect to TripIt. Please try again later."
It's been like this for several days now.

**Comment by jpatokal** [comment]
**Commented by jpatokal on 2013-03-26 11:12 UTC**
Yes, this is a known issue in the Tripit API: https://github.com/tripit/api/issues/54

**Comment by jpatokal** [comment]
**Updated by jpatokal on 2013-04-30 05:49 UTC**
- **status**: open --> closed-fixed
- **Group**:  --> v1.0_(example)

**Comment by jpatokal** [comment]
**Commented by jpatokal on 2013-04-30 05:49 UTC**
Fixed!  (Quite a while back at that.)

**Comment by BYVoid** [comment]
Now we have this error once again.

```
Could not connect to TripIt. Please try again later.
```
