### ISSUE TITLE
[Bug] London Heathrow KML issue [sf#156]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#156]
**Reported by stuwy on 2013-04-30 07:42 UTC**
I had searched London Heathrow. Downloaded the KML. This is what I got when I opened the KML file in Google earth. Kindly have a look. It does not represent the same information as the browser. I have highlighted this to Jani before. Not sure if there is a reason for this?

**Comment by jpatokal** [comment]
**Commented by stuwy on 2013-04-30 07:43 UTC**
screenshot of the browser: search -- > London Heathrow
Attached file Screen%20Shot%202013-04-30%20at%2008.38.18.png:

The file could not be attached: 'ascii' codec can't decode byte 0x89 in position 4: ordinal not in range(128)

**Comment by jpatokal** [comment]
**Commented by mato1 on 2013-05-02 00:44 UTC**
This issue is true for many airports.  I displayed the routes for Chicago (ORD) in the browser, clicked to download the KML, opened in Google Earth and it shows incorrect routes.

The KML file appears to be the same routes as the "recently added flights" that show up as the default routes when you first navigate to openflights.org

**Comment by jpatokal** [comment]
**Updated by jpatokal on 2013-05-16 03:25 UTC**
- **status**: open --> accepted
- **Priority**: 9 --> 5

**Comment by jpatokal** [comment]
**Commented by jpatokal on 2013-05-16 03:25 UTC**
KML exports are currently only supported for your own flights, and the "KML" button should be disabled when viewing route maps.

**Comment by chrisrosset** [comment]
Merging into #376.
