### ISSUE TITLE
[Bug] Hatfield Aerodrome needs removing [sf#183]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#181]
**Reported by *anonymous on 2014-05-12 16:33 UTC**
Hatfield needs removing from the database. It closed in the early 1990's. It was the former De Havilland development facility, famous for being the location that the first commercial jet, the De Havilland Comet was developed.

British Aerospace became owners and left it to rot, until the University of Hertfordshire bought the entire land in the mid 1990's. Since then the runway was removed and replaced with sports courts, the main hanger is now a gym and several smaller hangers are now used for shops, a police station and housing. The remaing areas of the site were demolished and returned to grassland or housing. 

More details can be found on the wiki page: http://en.wikipedia.org/wiki/Hatfield_Aerodrome

**Comment by jpatokal** [comment]
**Commented by *anonymous on 2014-08-10 05:33 UTC**
Some people flew out of this airfield back in the days when it was operational so this entry shouldn't be removed.

**Comment by chrisrosset** [comment]
Historical airport.
