### ISSUE TITLE
[Bug] DOH code now assigned to Hamad International [sf#185]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#183]
**Reported by strainu on 2014-06-11 12:36 UTC**
IATA code DOH is now assigned to Hamad International Airport (ICAO: OTHH) instead of the old airport. Check out https://www.iata.org/publications/Pages/code-search.aspx for confirmation.

**Comment by chrisrosset** [comment]
The data for DOH/OTHH has been updated in the database and in the dat file (2431d4d4089c1ab5ae41e56e03d331347b3a65dc). This issue can be closed.
