### ISSUE TITLE
[Bug] The AirLituanica carier is missing in DB (unable to add it mannually as it uses the same codes as a historic carrier). [sf#187]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#185]
**Reported by *anonymous on 2014-07-20 21:46 UTC**
Please add the AirLituanica (LT/LTU) airline to DB. It currently uses codes from historic LTU International company.
PS: http://www.airlituanica.com/en/

**Comment by digitalfan** [comment]
AirLituanica has ceased operations in the meantime, but I would nevertheless appreciate a possibility to select them as (historic) airline.

**Comment by jpatokal** [comment]
Added, thank you!
