### ISSUE TITLE
[Bug] Wrong time zone for Moscow [sf#202]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#200]
**Reported by *anonymous on 2014-11-29 21:26 UTC**
Dear Sirs! From October 26th 2014 Moscow is CET+2 zone, so calculation of flight duration became wrong. To make things more complicate, Russia will not implement daylight saving for next years (can't guarantee -- you know this empty-headed lawmakers, but as decided for now), so from April 26th it will be CET+1
Best regrds

**Comment by jpatokal** [comment]
**Commented by *anonymous on 2015-05-31 20:51 UTC**
Hello,

I want to correct this issue and provide more details.

Moscow timezone changed to UTC+3 permanently at 1414274400 unixtime (25 Oct 2014 22:00:00 UTC). Daylight saving time will not be used anymore.

All changes (for all 11 Russian timezones) have already added to fresh tzdata database. So all we need is to upgrade it.

**Comment by jpatokal** [comment]
Russian timezones have been updated and DST removed.  Thank you!

**Comment by serpent849** [comment]
this still causes issues for my flight from 2013, the duration is counted incorrectly.

**Comment by serpent849** [comment]
Also, Belarus is on the same timezone as Moscow. The duration of my flights is counted incorrectly.

**Comment by serpent849** [comment]
Is it possible to allow users to edit both the time and duration, so that neither was changed to match the other?
