### ISSUE TITLE
Great circle mapping for long routes

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#222]
**Reported by jpatokal on 2008-09-16 07:00 UTC**
By joejones on Flyertalk:

In my lofty opinion, great circle mapping would make this a "FlightMemory killer," even if it were really rough (say, plotting four or five intermediate points on routes of more than 5000 km, or something like that).

The great circles don't make much of a difference if you're flying short-hauls or kangaroo routes all the time, but for frequent transpaccers like me they are a must-have.

**Comment by chrisrosset** [comment]
First implemented in 87250f9b4977c13a4a9063f8dea1f97615f9626a. This issue can be resolved.
