### ISSUE TITLE
DAFIF database error message

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#224]
**Reported by *anonymous on 2008-09-17 09:29 UTC**
When searching in the DAFIF database with "ALL" selected as country name, an error message pops up saying that the database is limited to the United States. This means that the user must select the US as country when searching DAFIF, adding a step to the airport importing process.

It isn't a fatal problem, but it sure is annoying.

**Comment by chrisrosset** [comment]
The search was improved at some point to relax this requirement.
