### ISSUE TITLE
Allow editing airports and airlines added by user

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#232]
**Reported by jpatokal on 2008-11-14 07:18 UTC**
Currently, adding new airports is a write-only operation, there is no way to correct mistakes after you hit "Save".  Users should be allowed to edit airports that they themselves have created, and designated superusers should be allowed to edit any airports.

**Comment by reedy** [comment]
This.. Is partially done? I think?

**Comment by chrisrosset** [comment]
This was done.
