### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#234]
**Reported by *anonymous on 2008-11-20 10:20 UTC**
Export flight data as txt, csv or xls, or whatever.

(Not yet implemented, right? Or did I overlook something?)

**Comment by reedy** [comment]
CSV import exists...

https://github.com/jpatokal/openflights/issues/1076 is my request for JSON

**Comment by chrisrosset** [comment]
CSV import was implemented in cc8dfd79bfd6a83795b43bc0f9c1c69d8b7f7d55.
