### ISSUE TITLE
Text interface (for mobiles, etc.)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#250]
**Reported by *anonymous on 2009-02-03 03:39 UTC**
A simple text-based interface to the OpenFlights database would be very useful -- for instance, when travel plans change en route, the user could input updates while sitting in the departure lounge or on the tarmac. It would also be useful for quick PC-based edits, just to save on rendering firepower.

**Comment by chrisrosset** [comment]
This is an ancient issue but FWIW...

This is better done by taking notes on your phone and updating the website later. Handling cases where you don't have connectivity (common when traveling internationally) would require a lot of development effort.
