### ISSUE TITLE
Statistics banner for own use

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#253]
**Reported by *anonymous on 2009-03-05 13:58 UTC**
I would love to see the possibility to get a statistics banner for use e.g. on a website or blog.

It shouldn't be too large and possibly show the number of flights, total flight duration and miles flown, like the flightmemory banner (http://my.flightmemory.com/banner2/rofra.gif\).

**Comment by chrisrosset** [comment]
This issue can be closed - it was implemented [here](eec0732450169ed466fd0d89db02a6e0f48d2fb2) in 2009.
