### ISSUE TITLE
Keep private trips really private

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#263]
**Reported by redjoe on 2010-01-02 07:44 UTC**
Trips that are set for private viewing still show up in the drop-down list of trips on the user's public page, even though the actual routing is hidden. If users really want to keep their private trips to themselves, the existence of the trip should also be hidden from public view...

**Comment by chrisrosset** [comment]
Based on my testing, I believe this has been fixed in the 13 years since this was reported. :)
