### ISSUE TITLE
Embeddable Maps

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#264]
**Reported by muzthe42nd on 2010-01-11 00:14 UTC**
While I love the ability to link to a particular trip, to allow trip report readers to see where I've been and what I flew on, it would be pretty cool to be able to post an embeddable map into a blog post. It'd look a bit more complete, saving the reader from clicking a link (I think a lot of people are fairly lazy in that regard). I'm envisioning a google maps style embeddable map which allows the user to move around and so on, but I realise that could cost you quite a bit in bandwidth and stuff, so maybe generate a static image for a trip showing the route which the user could upload to their own webspace?

Anyway, just an idea. Thanks for the great openflights!

**Comment by chrisrosset** [comment]
This idea was explored with the map widget code which was recently removed #1250. There are better solutions for this (the single trip use case) now elsewhere on the web.

Additionally, generating a static image can easily be done by the user by taking a screenshot. Not the most technically advanced solution but it works.
