### ISSUE TITLE
More than Top 50 in "Top 10" section

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#281]
**Reported by *anonymous on 2010-10-17 15:06 UTC**
In the "Top 10" section, the menu allows only selections up to Top 50. If someone is having a lot of airports in his log and would like to get a list of them, it would be useful to have a menu item with a greater number than 50 or even a menu item like "Show all".

**Comment by digitalfan** [comment]
This is a feature request I had added some time ago in the old system. The "Show all" button has already been added.
