### ISSUE TITLE
[Feature] Airports should include country code(ISO 3166-1 alpha-3) [sf#101]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#319]
**Reported by zhabar on 2014-08-07 11:13 UTC**
It would be great if all airports would have 3 letter country codes because Country names are language specific (and don't have any standard format).

That way, it would be possible to:
- relate openflights data to other sources which contain additional info about countries
- easily translate countries to other languages

I'm attaching a country name -> country code (ISO 3316-1 alpha-3) lookup csv table that has the same names of countries as in openflights database.

**Comment by jpatokal** [comment]
**Commented by jpatokal on 2014-08-07 12:28 UTC**
Not a bad idea, although there's a map of country names to several types of codes already in available:
https://sourceforge.net/p/openflights/code/HEAD/tree/openflights/data/countries.dat

**Comment by jpatokal** [comment]
**Commented by *anonymous on 2015-01-13 13:56 UTC**
The current solution - where countries are mapped by their names to codes - can't encode the small differences between the various common codings. These coding schemes define areas and each area is assigned to a code. These areas are only mostly identical across codings.

For example in ISO Palestine includes the Gaza Strip and the West Bank. Where the GEC code has entries for Gaza Strip and West Bank.

There is one airport in the Gaza Strip:
3969,"Yasser Arafat Intl","Gaza","Palestine","GZA","LVGZ",31.246389,34.276111,320,2,"U","Asia/Gaza"

The country mentioned there Palestine can't be mapped to the GEC codes. And the countries.dat file from above doesn't even contain an entry for Palestine (but entries for Gaza Strip and West Bank). 

I suggest if that would be possible to add columns for the most important codings directly to the airports.dat file. Each airport has a coordinate, and based on that coordinate it can be decided in which area of a coding it fits best.

Maybe I am mistaken, but in my opinion that would make using the airports data in a software product easier, because you don't have to deal with those small mapping differences.

Here is some information about using ISO 3316 codes in software solutions:
http://www.statoids.com/w3166use.html

**Comment by chrisrosset** [comment]
This is an old and stale issue but FWIW:

As far as `airports.dat` goes, changes to the format are unlikely at this point.

Using ISO codes is probably better than using country names but comes with its own problems.

The OurAirports dataset does contain codes for the country and region.
