### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#327]
It's 2015, and high time OpenFlights switched to use HTTPS.  Maybe with a free cert from Let's Encrypt once they launch in September?  https://letsencrypt.org/

**Comment by simonlbn** [comment]
It's 2016 and really time to switch to / support HTTPS. Especially considering it is potentially sensitive information you hold.

Even if you don't want to do Lets Encrypt (it's cool but has certain downsides), basic SSL certificates are cheap.

**Comment by andrewachen** [comment]
p.s. happy to pay for the SSL certificates; just let me know when you're ready to run it.

**Comment by jpatokal** [comment]
This is starting to look like it's worth an experiment:
https://certbot.eff.org/#ubuntutrusty-apache

**Comment by andrewachen** [comment]
I'm still happy to buy a 3 year cert if that's the only thing stopping us from deploying SSL.

**Comment by andrewachen** [comment]
Bump - can we please make this a thing? :(

**Comment by NickMOrlando** [comment]
+1

**Comment by jpatokal** [comment]
I'm *delighted* to announce this is now done, and OpenFlights not only supports HTTPS, but is HTTPS-only.  Certbot worked nicely, hat tip to Let's Encrypt and the EFF!

**Comment by NickMOrlando** [comment]
:+1:

**Comment by andrewachen** [comment]
Can you consider setting HSTS headers?

**Comment by simonlbn** [comment]
Thanks!
