### ISSUE TITLE
Missing airlines and routes

### ISSUE THREAD

**Issue by Sperry8** [jpatokal/openflights#330]
Hello,

Love openflights, thanks!  You are missing some airlines... for example, http://dniproavia.com/en/
You are also missing some connections on certain airlines.  For example, you show Ukraine International http://www.flyuia.com/eng/us.html but you don't correctly show all their routes.  For example, they have nonstop flights from Odessa that you do not show on the map (Kharkov for one).  Can you update?

**Comment by jpatokal** [comment]
No, I can't: the data comes from Airline Route Mapper, who have not updated in over a year now. http://arm.64hosts.com/

We're working on alternative sources of data, but this will be a slow process.
