### ISSUE TITLE
Switch airport update requests from sending emails to creating Github issues

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#332]
Currently airport updates get sent to a mailbox and processed randomly (and slowly).

if they were created as Github issues instead, they would be more visible (avoiding duplicate reports) and the workload of processing them could be shared.

**Comment by chrisrosset** [comment]
Done in https://github.com/jpatokal/openflights/commit/3126fed0d1267bc02964be27f51674df4d7cc213 and announced here: https://blog.openflights.org/2015/07/25/airport-edit-review-now-through-github/.
