### ISSUE TITLE
Error while importing from flightmemory

### ISSUE THREAD

**Issue by tiamsanit** [jpatokal/openflights#333]
I use firefox and IE to save as html and these are the error:
HTML create by firefox
OpenFlights: Import
Upload successful. Parsing...
Results
Tmpfile phpkt9FXs
ID  Date    Flight  From    To  Miles   Time    Plane   Reg Seat    Class   Type    Reason  Trip    Comment

however no actual flight imported.
HTML create by IE
OpenFlights: Import
Upload successful. Parsing...
Results
Tmpfile phpchKSBv
Sorry, the file /var/www/openflights/import/phpchKSBv does not appear contain FlightMemory FlightData.

best regards,

**Comment by UmpPCPL** [comment]
The same for me.  I can provide HTML sample.

**Comment by jpatokal** [comment]
I can confirm that something seems to be broken here, I'll try to take a look this week.

**Comment by jpatokal** [comment]
FlightMemory made a minor change to their formatting that broke the importer, I've fixed it so that both old and new style files should parse correctly now.  Please reopen if you're still having trouble.
