### ISSUE TITLE
Add column to airports data (for International airport vs National)

### ISSUE THREAD

**Issue by quentinsup** [jpatokal/openflights#361]
It will be very helpfull to have a column which indicates if the airport is International (I), National (N), Private (P) or something similar !

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by ordtpe:

UPDATE airports SET name='Beijing South Railway Station', city='Beijing', country='China', iata='', icao=NULL, x=116.3763, y=39.8658, elevation=144, timezone=8, dst='U' WHERE apid=9033;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Beijing South Railway Station
    [city] => Beijing
    [country] => China
    [iata] => 
    [icao] => 
    [x] => 116.3763
    [y] => 39.8658
    [elevation] => 144
    [apid] => 9033
    [uid] => 1551
    [timezone] => 8
    [dst] => N
    [tz_id] => Asia/Chongqing
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
Do you have a free worldwide data source for such information?

**Comment by quentinsup** [comment]
No :(

To my mind it was a main information usually directly attached to the airport...

But it should be possible to deduce it by inspection of the routes ("Private" means src_apid = dst_apid, "International" means country of the src aiport is different from country of the dst airport, "National" means no route to other countries).

What do you think about this ?

**Comment by jpatokal** [comment]
Download the database, write some SQL that does that, and I'll be more than happy to look at it :)

**Comment by quentinsup** [comment]
Perhaps something like that could helps (with new column named 'area') :

``` sql
SET SQL_SAFE_UPDATES = 0;

UPDATE airports SET area = "";

CREATE OR REPLACE VIEW aiarea1 AS 
    SELECT DISTINCT r1.src_apid as apid 
    FROM airports a1, airports a2, routes r1 
    WHERE r1.src_apid = a1.apid AND r1.dst_apid = a2.apid AND a1.country <> a2.country;

UPDATE airports SET area = "I" WHERE apid IN (SELECT DISTINCT apid FROM aiarea1);
UPDATE airports SET area = "N" WHERE apid NOT IN (SELECT DISTINCT apid FROM aiarea1);

DROP VIEW aiarea1;
SET SQL_SAFE_UPDATES = 1;
```

**Comment by chrisrosset** [comment]
Closing this issue as stale.

Inferring this from routes is a cool idea but you'd need extremely high quality route information just to distinguish national vs international reliably.

OurAirports does not have this available in their dataset.
