### ISSUE TITLE
CA added direct flights from AKL to PEK

### ISSUE THREAD

**Issue by leggewie** [jpatokal/openflights#363]
CA will start flying direct daily between AKL and PEK in January

**Comment by jpatokal** [comment]
Route data is not maintained by OpenFlights: it's sourced from a third party, which has unfortunately not updated it for over a year.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by ChrisGE:

UPDATE airports SET name='Pek', city='Beijing', country='China', iata='PEK', icao=NULL, x=116.407222, y=39.904167, elevation=171, timezone=8, dst='U' WHERE apid=8595;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Capital Intl
    [city] => Beijing
    [country] => China
    [iata] => PEK
    [icao] => ZBAA
    [x] => 116.584556
    [y] => 40.080111
    [elevation] => 116
    [apid] => 3364
    [uid] => 
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Chongqing
)

Array
(
    [name] => All Airports
    [city] => Beijing
    [country] => China
    [iata] => BJS
    [icao] => 
    [x] => 116.407222
    [y] => 39.904167
    [elevation] => 171
    [apid] => 8595
    [uid] => 5329
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Chongqing
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by victorzheung:

UPDATE airports SET name='PEK', city='Beijing', country='China', iata='PEK', icao=NULL, x=116.407222, y=39.904167, elevation=171, timezone=8, dst='U' WHERE apid=8595;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Beijing Capital International Airport
    [city] => Beijing
    [country] => China
    [iata] => PEK
    [icao] => ZBAA
    [x] => 116.58499908447266
    [y] => 40.080101013183594
    [elevation] => 116
    [apid] => 3364
    [uid] => 
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Shanghai
    [type] => airport
    [source] => OurAirports
)

Array
(
    [name] => All Airports
    [city] => Beijing
    [country] => China
    [iata] => BJS
    [icao] => 
    [x] => 116.407222
    [y] => 39.904167
    [elevation] => 171
    [apid] => 8595
    [uid] => 5329
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Shanghai
    [type] => airport
    [source] => User
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by victorzheung:

UPDATE airports SET name='Beijing International Airport', city='Beijing', country='China', iata='PEK', icao=NULL, x=116.407222, y=39.904167, elevation=171, timezone=8, dst='U' WHERE apid=8595;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Beijing Capital International Airport
    [city] => Beijing
    [country] => China
    [iata] => PEK
    [icao] => ZBAA
    [x] => 116.58499908447266
    [y] => 40.080101013183594
    [elevation] => 116
    [apid] => 3364
    [uid] => 
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Shanghai
    [type] => airport
    [source] => OurAirports
)

Array
(
    [name] => All Airports
    [city] => Beijing
    [country] => China
    [iata] => BJS
    [icao] => 
    [x] => 116.407222
    [y] => 39.904167
    [elevation] => 171
    [apid] => 8595
    [uid] => 5329
    [timezone] => 8
    [dst] => U
    [tz_id] => Asia/Shanghai
    [type] => airport
    [source] => User
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI
