### ISSUE TITLE
Update airport Rajiv Gandhi International Airport (HYD/VOHS)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#368]
New airport edit suggestion submitted by akumanduri:

UPDATE airports SET name='Rajiv Gandhi International Airport', city='Hyderabad', country='India', iata='HYD', icao='VOHS', x=78.431, y=17.254, elevation=2028, timezone=5.5, dst='N' WHERE apid=3141;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Hyderabad
    [city] => Hyderabad
    [country] => India
    [iata] => HYD
    [icao] => VOHY
    [x] => 78.467586
    [y] => 17.453117
    [elevation] => 1742
    [apid] => 3141
    [uid] => 
    [timezone] => 5.5
    [dst] => N
    [tz_id] => Asia/Calcutta
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/VOHS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20VOHS%20airport&btnI

**Comment by davidjohnson6** [comment]
New name and ICAO is correct

**Comment by chrisrosset** [comment]
This has been updated.
