### ISSUE TITLE
Update airport Tuzla (TZL/LQTZ)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#369]
New airport edit suggestion submitted by G-GFFD:

UPDATE airports SET name='Tuzla', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.4329, y=44.2731, elevation=1100, timezone=1, dst='E' WHERE apid=1646;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Sarajevo
    [city] => Sarajevo
    [country] => Bosnia and Herzegovina
    [iata] => SJJ
    [icao] => LQSA
    [x] => 18.331467
    [y] => 43.824583
    [elevation] => 1708
    [apid] => 1646
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by jaydee:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.724667, 44.458721, 784,  1, 'E', 1960);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by nicevolley:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla International Airport', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.7247, 44.4586, 784,  1, 'E', 37114);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by nicevolley:

UPDATE airports SET name='Tuzla', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.724783, y=44.458656, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by nicevolley:

UPDATE airports SET name='Tuzla', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.724783, y=44.458656, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by julian09:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla International Airport', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.724722, 44.458611, 765,  1, 'E', 15140);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by julian09:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla International Airport', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.724722, 44.458611, 765,  1, 'E', 15140);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by aviatores:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla International Airport', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.4329, 44.2731, 765,  1, 'E', 40652);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by aviatores:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.4329, 44.2731, 765,  1, 'E', 40652);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by aviatores:

UPDATE airports SET name='Tuzla', city='Null', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.724783, y=44.458656, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.724783
    [y] => 44.458656
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

INSERT INTO airports(name,city,country,iata,icao,x,y,elevation,timezone,dst,uid) VALUES('Tuzla', 'Tuzla', 'Bosnia and Herzegovina', 'TZL', 'LQTZ', 18.724722, 44.458611, 765,  2, 'E', 41229);

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

UPDATE airports SET name='Tuzla International Airport', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

UPDATE airports SET name='Hobart Harbour', city='Hobart', country='Australia', iata=NULL, icao=NULL, x=147.509994507, y=-42.836101532, elevation=13, timezone=10, dst='O' WHERE apid=3336;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Hobart International Airport
    [city] => Hobart
    [country] => Australia
    [iata] => HBA
    [icao] => YMHB
    [x] => 147.509994507
    [y] => -42.836101532
    [elevation] => 13
    [apid] => 3336
    [uid] => 
    [timezone] => 10
    [dst] => O
    [tz_id] => Australia/Melbourne
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

UPDATE airports SET name='Hobart Harbour', city='Hobart', country='Australia', iata=NULL, icao=NULL, x=147.509994507, y=-42.836101532, elevation=13, timezone=10, dst='O' WHERE apid=3336;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Hobart International Airport
    [city] => Hobart
    [country] => Australia
    [iata] => HBA
    [icao] => YMHB
    [x] => 147.509994507
    [y] => -42.836101532
    [elevation] => 13
    [apid] => 3336
    [uid] => 
    [timezone] => 10
    [dst] => O
    [tz_id] => Australia/Melbourne
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

UPDATE airports SET name='Tuzla International Airport', city='Tuzla', country='Bosnia and Herzegovina', iata=NULL, icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tomflieger:

UPDATE airports SET name='Tuzla International Airport', city='Tuzla', country='Bosnia and Herzegovina', iata=NULL, icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by josmon10:

UPDATE airports SET name='Foz do Iguacu Heliport', city='Foz Do Iguacu', country='Brazil', iata=NULL, icao=NULL, x=-54.481524, y=-25.612910, elevation=786, timezone=-3, dst='S' WHERE apid=2554;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Cataratas International Airport
    [city] => Foz Do Iguacu
    [country] => Brazil
    [iata] => IGU
    [icao] => SBFI
    [x] => -54.48500061035156
    [y] => -25.600278854370117
    [elevation] => 786
    [apid] => 2554
    [uid] => 
    [timezone] => -3
    [dst] => S
    [tz_id] => America/Sao_Paulo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by devmind:

UPDATE airports SET name='Tuzla International Airport', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by dben:

UPDATE airports SET name='LUX', city='LUX South Ari Atoll', country='Maldives', iata=NULL, icao=NULL, x=72.8962, y=3.4987, elevation=0, timezone=5, dst='N' WHERE apid=13196;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => LUX
    [city] => LUX South Ari Atoll
    [country] => Maldives
    [iata] => 
    [icao] => 
    [x] => 72.8962
    [y] => 3.4987
    [elevation] => 0
    [apid] => 13196
    [uid] => 1970
    [timezone] => 0
    [dst] => U
    [tz_id] => 
    [type] => 
    [source] => 
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by qube:

UPDATE airports SET name='Tuzla International Airport', city='Tuzla', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by foxyankee:

UPDATE airports SET name='Tuzla International Airport', city='Null', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by foxyankee** [comment]
Can someone PLEASE update this airport with the IATA code TZL please?!

Thank you!

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by foxyankee:

UPDATE airports SET name='Tuzla International Airport', city='Null', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by dutydroid:

UPDATE airports SET name='Tuzla International Airport', city='Null', country='Bosnia and Herzegovina', iata='TZL', icao='LQTZ', x=18.72480010986328, y=44.45869827270508, elevation=784, timezone=1, dst='E' WHERE apid=6947;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => 
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by dutydroid** [comment]
the update suggestion is to add the value for 
[city] =>Tuzla 
At the moment Null is saved!
And additionally type is set 'unknown'

UPDATE airports SET city='Tuzla', type='airport'

Thanks.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by garyhembyjones@gmail.com:

Array
(
    [apid] => 6947
    [name] => Tuzla International Airport
    [city] => Dubrave Gornje
    [country] => Bosnia and Herzegovina
    [iata] => TZL
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [timezone] => 1
    [dst] => E
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tuzla International Airport
    [city] => Null
    [country] => Bosnia and Herzegovina
    [iata] => TZL
    [icao] => LQTZ
    [x] => 18.72480010986328
    [y] => 44.45869827270508
    [elevation] => 784
    [apid] => 6947
    [uid] => 2319
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Sarajevo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/LQTZ/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20LQTZ%20airport&btnI

**Comment by chrisrosset** [comment]
This ticket is a bit all over the place for various different reasons. Still, most of the updates (most, importantly the TZL code) have been applied since the issue was raised in 2015.
