### ISSUE TITLE
Update airports Doha (OTBD, OTHH/DOH)

### ISSUE THREAD

**Issue by donshamal** [jpatokal/openflights#372]
There is currently a single Doha airport in the database - the old one:
Doha International, DOH/OTBD.

I would like to record separately flights I've taken from the old and new airports. This is complicated by the fact that the old airport lost its IATA code to the new airport; it seems also to have lost its ICAO code - though the new airport is using a different one.

As such, I'd suggest the two airports on the system should be:

Doha International
IATA: -
ICAO: OTBD

Hamad International
IATA: DOH
ICAO: OTHH

I thought I'd ask if this can be implemented. [Needless to say, I'm assuming that, once changed, I would have to manually switch some of my Doha flights to the correct airport.]

Thanks in advance

**Comment by jpatokal** [comment]
Done, thank you!
