### ISSUE TITLE
Update airport Wichita Dwight D. Eisenhower (ICT/KICT)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#377]
New airport edit suggestion submitted by actruong:

UPDATE airports SET name='Wichita Dwight D. Eisenhower', city='Wichita', country='United States', iata='ICT', icao='KICT', x=-97.433056, y=37.649944, elevation=1333, timezone=-6, dst='A' WHERE apid=3457;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Wichita Mid Continent
    [city] => Wichita
    [country] => United States
    [iata] => ICT
    [icao] => KICT
    [x] => -97.433056
    [y] => 37.649944
    [elevation] => 1333
    [apid] => 3457
    [uid] => 
    [timezone] => -6
    [dst] => A
    [tz_id] => America/Chicago
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KICT/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KICT%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by cheng8542:

UPDATE airports SET name='Castries Port', city='Castries', country='Saint Lucia', iata='', icao=NULL, x=-60.995183, y=14.014653, elevation=0, timezone=-4, dst='N' WHERE apid=2893;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => George F L Charles
    [city] => Castries
    [country] => Saint Lucia
    [iata] => SLU
    [icao] => TLPC
    [x] => -60.992936
    [y] => 14.020228
    [elevation] => 22
    [apid] => 2893
    [uid] => 
    [timezone] => -4
    [dst] => U
    [tz_id] => America/St_Lucia
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by cheng8542:

UPDATE airports SET name='Castries Cruiseship Terminal', city='Castries', country='Saint Lucia', iata='', icao=NULL, x=-60.995183, y=14.014653, elevation=0, timezone=-4, dst='N' WHERE apid=2893;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => George F L Charles
    [city] => Castries
    [country] => Saint Lucia
    [iata] => SLU
    [icao] => TLPC
    [x] => -60.992936
    [y] => 14.020228
    [elevation] => 22
    [apid] => 2893
    [uid] => 
    [timezone] => -4
    [dst] => U
    [tz_id] => America/St_Lucia
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by chrisrosset** [comment]
ICT has been updated since. Dismissing the other updates as stale/invalid.
