### ISSUE TITLE
Update airport Tan Son Nhat Intl (SGN/VVTS)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#381]
New airport edit suggestion submitted by MarkSen:

UPDATE airports SET name='Tan Son Nhat Intl', city='Ho Chi Minh City', country='Vietnam', iata='SGN', icao='VVTS', x=106.651856, y=10.818797, elevation=33, timezone=7, dst='U' WHERE apid=3205;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Tansonnhat Intl
    [city] => Ho Chi Minh City
    [country] => Vietnam
    [iata] => SGN
    [icao] => VVTS
    [x] => 106.651856
    [y] => 10.818797
    [elevation] => 33
    [apid] => 3205
    [uid] => 
    [timezone] => 7
    [dst] => U
    [tz_id] => Asia/Saigon
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/VVTS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20VVTS%20airport&btnI

**Comment by davidjohnson6** [comment]
New name is correct

**Comment by chrisrosset** [comment]
This has been updated.
