### ISSUE TITLE
Update airport Heathrow (LGW/EGLL)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#387]
New airport edit suggestion submitted by DavidJHarvey:

UPDATE airports SET name='Heathrow', city='London', country='United Kingdom', iata='LGW', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Gatwick
    [city] => London
    [country] => United Kingdom
    [iata] => LGW
    [icao] => EGKK
    [x] => -0.190278
    [y] => 51.148056
    [elevation] => 202
    [apid] => 502
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by DavidJHarvey:

UPDATE airports SET name='Gatwick', city='London', country='United Kingdom', iata='LGW', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Gatwick
    [city] => London
    [country] => United Kingdom
    [iata] => LGW
    [icao] => EGKK
    [x] => -0.190278
    [y] => 51.148056
    [elevation] => 202
    [apid] => 502
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by DavidJHarvey:

UPDATE airports SET name='Gatwick', city='London', country='United Kingdom', iata='LGW', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Gatwick
    [city] => London
    [country] => United Kingdom
    [iata] => LGW
    [icao] => EGKK
    [x] => -0.190278
    [y] => 51.148056
    [elevation] => 202
    [apid] => 502
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by DavidJHarvey:

UPDATE airports SET name='Gatwick', city='London', country='United Kingdom', iata='LGW', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Gatwick
    [city] => London
    [country] => United Kingdom
    [iata] => LGW
    [icao] => EGKK
    [x] => -0.190278
    [y] => 51.148056
    [elevation] => 202
    [apid] => 502
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by DavidJHarvey:

UPDATE airports SET name='London-Gatwick', city='London', country='United Kingdom', iata='LHR', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by davidjohnson6** [comment]
Data from DavidJHarvey is incorrect. Heathrow is LHR while Gatwick is LGW.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by sapun:

UPDATE airports SET name='Heathrow', city='London', country='United Kingdom', iata='LHR', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by sapun:

UPDATE airports SET name='Heathrow', city='London', country='United Kingdom', iata='LHR', icao='EGLL', x=-0.461389, y=51.4775, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Heathrow
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461389
    [y] => 51.4775
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Fabdur:

UPDATE airports SET name='London Heathrow Airport', city='London', country='United Kingdom', iata='LHR', icao='EGLL', x=-0.461941, y=51.4706, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => London Heathrow Airport
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461941
    [y] => 51.4706
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Fabdur:

UPDATE airports SET name='London Heathrow Airport', city='London', country='United Kingdom', iata='LHR', icao='EGLL', x=-0.461941, y=51.4706, elevation=83, timezone=0, dst='E' WHERE apid=507;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => London Heathrow Airport
    [city] => London
    [country] => United Kingdom
    [iata] => LHR
    [icao] => EGLL
    [x] => -0.461941
    [y] => 51.4706
    [elevation] => 83
    [apid] => 507
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/London
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EGLL/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EGLL%20airport&btnI
