### ISSUE TITLE
Duplicates/Remove some rows

### ISSUE THREAD

**Issue by bufdev** [jpatokal/openflights#390]
Just wanted to put this out there as I went through this manually :)

I was working on a version where I would have all airports/airlines/routes unique on both iata and icao codes, and came up with this: https://github.com/peter-edge/go-openflights/blob/master/filters.go

Some of the IDs listed are direct duplicates, and some of the data seems old - the requirements for this application are more about active objects (ie I pre-filter inactive airlines, for example), but I thought you might want to check out these IDs as it is.

**Comment by jpatokal** [comment]
All duplicate airport IATA & ICAO codes removed, so closing.

Note that airlines are a different kettle of fish, since IATA allows "controlled duplicates" (sigh...).
