### ISSUE TITLE
Wrong TZ entries for airports near Cancun

### ISSUE THREAD

**Issue by martijnhoekstra** [jpatokal/openflights#391]
The airports in/near Cancun (CZM, ZTM, ISJ) are listed as America/Mexico_City but should be America/Cancun (offset and DST rules are identical). I tried to correct this in the editor on the website, but was unable to find a way to enter a timezone id for an airport.

**Comment by jpatokal** [comment]
Timezone IDs are determined with periodic runs of a helper script.  I've updated all airports in Mexico, thanks!
