### ISSUE TITLE
Doha International Airport has closed and been replaced by Hamad International Airport

### ISSUE THREAD

**Issue by chealy** [jpatokal/openflights#393]
Doha International Airport (IATA: DOH, ICAO: OTBD) (Arabic: مطار الدوحة الدولي‎) was an airport in Doha, Qatar. It was Qatar's commercial airport until Hamad International Airport opened on 30 April 2014.

Doha has closed and been replaced by Hamad:

https://en.wikipedia.org/wiki/Doha_International_Airport

The following changes should probably be made to the database:

@@ -2184,7 +2184,7 @@
 2237,"Deir Zzor","Deire Zor","Syria","DEZ","OSDZ",35.285374,40.175961,700,2,"E","Asia/Damascus"
 2239,"Bassel Al Assad Intl","Latakia","Syria","LTK","OSLK",35.401094,35.948681,157,2,"E","Asia/Damascus"
 2240,"Palmyra","Palmyra","Syria","PMS","OSPR",34.557361,38.316889,1322,2,"E","Asia/Damascus"
-2241,"Hamad Intl","Doha","Qatar","DOH","OTHH",25.273056,51.608056,13,3,"U","Asia/Qatar"
+2241,"Doha Intl","Doha","Qatar","DOH","OTBD",25.261125,51.565056,35,3,"U","Asia/Qatar"
 2242,"Canton","Canton Island","Kiribati","CIS","PCIS",-2.768122,-171.710394,9,13,"U","Pacific/Enderbury"
 2243,"Rota Intl","Rota","Northern Mariana Islands","ROP","PGRO",14.174308,145.242536,607,10,"U","Pacific/Saipan"
 2244,"Francisco C Ada Saipan Intl","Saipan","Northern Mariana Islands","SPN","PGSN",15.119003,145.729356,215,10,"U","Pacific/Saipan"

**Comment by jpatokal** [comment]
Done by adding Hamad Intl as a new airport with code DOH.
