### ISSUE TITLE
SEL airport code

### ISSUE THREAD

**Issue by bmomjian** [jpatokal/openflights#403]
I believe the SEL airport code for Gimpo is wrong in airports.dat here:

https://github.com/jpatokal/openflights/blob/master/data/airports.dat

Since 2009, "SEL" is the Seoul "All Airports" code for Seoul, and "GMP" is the Gimpo code.  For confirmation, see 

https://en.wikipedia.org/wiki/Gimpo_International_Airport

For reference see:

http://www.airliners.net/aviation-forums/general_aviation/print.main?id=4568138.

Thanks.  Your list is very helpful, and I have donated.

**Comment by bmomjian** [comment]
Oh, one more problem.  The "MOW" line looks wrong:

    8193,"MOW","Moscow","Russia","MOW",\N,55.7557,37.6176,0,4,"N","Europe/Moscow"

I think the first "MOW" should be "All Airports" to match other entries like CHI.

**Comment by davidjohnson6** [comment]
Agree with bmomjian

**Comment by bmomjian** [comment]
SEL has been removed from the current airports.dat file, and Gimpo is now GMP, so this item can be closed.
