### ISSUE TITLE
Quintana Roo, Mexico time zone incorrect

### ISSUE THREAD

**Issue by aschuett** [jpatokal/openflights#406]
Quintana Roo Mexico changed time zones on Feb 1, 2015 to a static UTC-5.  This seems to not be reflected in current code, as a flight from CUN-MIA which should be indicated as 1h11m at this time is shown as 2h11m.

**Comment by jpatokal** [comment]
All airports in Mexico/Cancun have been set to -5 for some time?  This may be a DST issue...
