### ISSUE TITLE
Error Airport name at 8510

### ISSUE THREAD

**Issue by chadliu23** [jpatokal/openflights#417]
8510,"International Airport","Ocala","United States","OCF","KOCF",29.1725,-82.224167,89,-5,"A","America/New_York"

should be 

8510,"Ocala International Airport","Ocala","United States","OCF","KOCF",29.1725,-82.224167,89,-5,"A","America/New_York"

**Comment by jpatokal** [comment]
As explained previously, "name" is not meant to stand alone, but is combined with "city".
