### ISSUE TITLE
Airport 503 error

### ISSUE THREAD

**Issue by chadliu23** [jpatokal/openflights#418]
503,"City","London","United Kingdom","LCY","EGLC",51.505278,0.055278,19,0,"E","Europe/London"

should be

503,"London City Airport","London","United Kingdom","LCY","EGLC",51.505278,0.055278,19,0,"E","Europe/London"

**Comment by jpatokal** [comment]
No, that's correct, the intended output format is "City-Name" which in this case is "London-City".  "Airport" is unnecessary.

**Comment by chadliu23** [comment]
I mean "City" as airport name is insufficient and very easy to be confused. 

My suggestion: change to "London City"  or "London City Airport" 

Airport in the airport name flied is very common in the data.
