### ISSUE TITLE
Missing airports: BEF and WAE

### ISSUE THREAD

**Issue by fmanchon** [jpatokal/openflights#480]
Hi there, I just downloaded the airports database.  This is great stuff. BEF and WAE are missing, I found them in OurAirports as follows:

4770    MNBL    medium_airport  Bluefields Airport  11.99100018 -83.77410126    20  NA  NI  NI-AS   Bluefileds  yes MNBL    BEF         http://en.wikipedia.org/wiki/Bluefields_Airport 

5127    OEWD    medium_airport  Wadi Al Dawasir Airport 20.50429916 45.19960022 2062    AS  SA  SA-01       yes OEWD    WAE         http://en.wikipedia.org/wiki/Wadi_al-Dawasir_Domestic_Airport

**Comment by fmanchon** [comment]
Sorry, I made a typo.  BEF is listed.  _BFE_ is missing:

2242    EDLI    small_airport   Bielefeld Airport   51.96472168 8.544444084 433 EU  DE  DE-NW   Bielefeld   no  EDLI    BFE     http://www.flugplatz-bielefeld.de/  http://de.wikipedia.org/wiki/Flugplatz_Bielefeld    Flugplatz-Windelsbleiche

**Comment by fmanchon** [comment]
OK, I made up the missing records myself, here they are.

<table>
<tr><td>9542</td><td>Bielefeld Airport</td><td> Bielefeld</td><td>  Germany</td><td>    BFE</td><td>    EDLI</td><td>   51.96472168</td><td>    8.544444084</td><td>    433</td><td>    1</td><td>  E</td><td>  Europe/Berlin</td></tr>
<tr><td>9543</td><td>   Wadi Al Dawaser Airport </td><td>Wadi al Dawaser</td><td>   Saudi Arabia</td><td>   WAE</td><td>    OEWD</td><td>   20.50429916</td><td>    45.19960022</td><td>    2062</td><td>   3</td><td>  U</td><td>  Asia/Riyadh</td></tr>
</table>

**Comment by fmanchon** [comment]
Not sure about the units to be used for altitude. I used meters.

**Comment by jpatokal** [comment]
Thank you for the bug report.  I'm actually planning to do a bulk import/sync with OurAirports soon (issue #481), which should fix this and a number of other issues.
