### ISSUE TITLE
Not only airports are listed

### ISSUE THREAD

**Issue by tiborh** [jpatokal/openflights#482]
In airports.dat there are at least two lines not connected to airports:

8886    "Budapest Keteli"   "Budapest"  "Hungary"   ""
8940    "Budapest Keleti pu."   "Budapest"  "Hungary"   ""

8940 is a railway station
8886 is a misspelled variety of 8940
(other records not having airport code may have the same problem)

**Comment by jpatokal** [comment]
Yes, not all entities in "airports.dat" are airports.  See issue 500.
