### ISSUE TITLE
CSV Import Airline issue

### ISSUE THREAD

**Issue by kballenegger** [jpatokal/openflights#498]
I imported data from a CSV file I had, and added the rest by hand. The CSV listed the "airline" as its IATA code (e.g. UA / LX etc). The airline was not recognized. Is there a way to bulk fix these airline misclassifications?

![image](https://cloud.githubusercontent.com/assets/307861/14133593/579a0904-f605-11e5-8124-23050f64e7aa.png)

**Comment by jpatokal** [comment]
Working as intended: the airline field should contain the airline's name, not a code.

You could export all your flights as CSV, fix up the airlines in your editor of choice (be sure to remove the Airline_OID value for these rows, as it will otherwise override the new values), then import again.
