### ISSUE TITLE
The flight time from TNG to GIB is wrong

### ISSUE THREAD

**Issue by BYVoid** [jpatokal/openflights#499]
From: TNG
To: GIB
Distance: 69
Time: 23:50

I guess this is because of TNG is in GMT+0 and GIB is in GMT+1, while the flight time is less than an hour.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Tatti:

UPDATE airports SET name='Dusseldorf ', city='Dusseldorf', country='Germany', iata='', icao=NULL, x=6.7683, y=51.2791, elevation=155, timezone=1, dst='E' WHERE apid=10917;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Dusseldorf Airport Terminal Station
    [city] => Dusseldorf
    [country] => Germany
    [iata] => 
    [icao] => 
    [x] => 6.7683
    [y] => 51.2791
    [elevation] => 155
    [apid] => 10917
    [uid] => 5329
    [timezone] => 1
    [dst] => E
    [tz_id] => 
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI
