### ISSUE TITLE
Import Calendar.ics from Kayak

### ISSUE THREAD

**Issue by psbaj** [jpatokal/openflights#509]
All the history of my flights are stored at KAYAK Trips tool. They have an export option that creates a file with the extension .ICS that can't be imported to OpenFlights. Is it possible to create the function that import this type of file?

**Comment by jpatokal** [comment]
ICS is iCalendar format, which is nowhere near any of the existing formats, so no, this is not going to happen unless somebody wants to contribute the code to make it happen.
