### ISSUE TITLE
CSV import ignores duration when no miles set

### ISSUE THREAD

**Issue by lucianf** [jpatokal/openflights#523]
I'm importing a CSV (same structure as exported from Openflights), which has flight date (date + time) and duration (as calculated by me from the departure/arrival times [*]), but no miles.  The import tool overrides the duration as calculated by the algorithm.  If I fill in the miles in the CSV then the duration is no longer overridden.

[*] Also, a feature request please: support supplying arrival time in the CSV instead of the duration.  The duration may be missing in bookings, but the departure/arrival times are certainly included - so it should make importing flights easier.

**Comment by chrisrosset** [comment]
FWIW, this is now fixed on master and will hopefully be released soon.
