### ISSUE TITLE
Chrome/Firefox not working correctly

### ISSUE THREAD

**Issue by thegrailer** [jpatokal/openflights#526]
I  can't seem to get openflights to work on either Firefox or Chrome.  Works on Tor and IE.   

Firefox: Page opens but it's a white rectangle with openflights.org logo outside of it in the top right corner of the page.  About/FAQ/Blog and the language box under the logo.  Turning off No Script, i.e., allow all of page doesn't help.  Ghostery isn't blocking anything. Ublock isn't blocking anything.  Flash is allowed. Nothing going on with Better Privacy.  Indeed, disabling all extensions had did not help.  Plug ins are all ask to activate.

Chrome: Entire page loads and I can log in but then almost noting.  None of the buttons are active except Logout.  I can move and zoom on the map.  Plus, if I click a city, e.g. CAI, the three buttons work (List my flights, Map of routes ..., and view airport details).  The search box also works.

Firefox screen shot:
![image](https://cloud.githubusercontent.com/assets/19310834/15189353/36a6197e-1778-11e6-812b-316925de6442.png)

Cheers

**Comment by jpatokal** [comment]
So there's something definitely wrong with your setup, because a) nobody else has reported this and b) I use Chrome myself.  The website uses no plugins, but does require Javascript.

I'd suggest you capture a HAR dump of what Chrome is doing when you try to load the page, which will likely pinpoint the error: https://collaborne.atlassian.net/wiki/pages/viewpage.action?pageId=38404124

**Comment by thegrailer** [comment]
What am I looking for in the HAR analyzer? Not sure exactly what was captured so I don't know what to look for - thanks (P.S. -- wouldn't call it something "wrong" --- different sounds better since it works well in other situations:))

Another point:  In Chrome the buttons work, "Analyze" and "Top 10" if I don't log in.  Once logged in, nothing.

**Comment by jpatokal** [comment]
Please attach the dump to this bug.  (Please make sure you're not logging in during the dump though, unless you want to share your login credentials with the world...)

**Comment by thegrailer** [comment]
I'll make sure that I enter my credit card too.  Any card in particular that you want the info for? :)
Will do later when I can access what I need -- cheers and thanks.

**Comment by thegrailer** [comment]
Had to make the har file into a zip to attach

Cheers

[openflights.org.zip](https://github.com/jpatokal/openflights/files/268957/openflights.org.zip)

**Comment by thegrailer** [comment]
Thoughts?
Cheers

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by VikingHenk:

UPDATE airports SET name='Dunedin City Octagon', city='Dunedin', country='New Zealand', iata=NULL, icao=NULL, x=170.503589, y=-45.874111, elevation=14, timezone=12, dst='Z' WHERE apid=2011;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Dunedin
    [city] => Dunedin
    [country] => New Zealand
    [iata] => DUD
    [icao] => NZDN
    [x] => 170.198333
    [y] => -45.928055
    [elevation] => 4
    [apid] => 2011
    [uid] => 
    [timezone] => 12
    [dst] => Z
    [tz_id] => Pacific/Auckland
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by thegrailer** [comment]
Is that reply is the correct thread?  Is my issue and airport issue?

**Comment by thegrailer** [comment]
One more try -- any updates re HAR dump?

Thanks

**Comment by thegrailer** [comment]
Last attempt at a reply.  I've tried here, twitter and FT.  Cheers -

**Comment by jpatokal** [comment]
Sorry for the delayed response.  I'm travelling and am unlikely be to able to look at this for several weeks.

**Comment by thegrailer** [comment]
sure -- hope you do reply otherwise it's back to a spreadsheet and flightmemory.

Cheers

**Comment by thegrailer** [comment]
Any chance that you are going to look at this?  It has been almost 2 months since I sent the Har file and a month since you said you'd be traveling (noticeably, other updates have been made).  I really need to update my travel logs and if you can't/aren't helping with your site, I'd appreciate you saying so.
Cheers -

**Comment by thegrailer** [comment]
I asked in May.  It's Nov.  I'm using your competitor and paying at logmyflight.net now.  Cheers
