### ISSUE TITLE
Update airport McGhee Tyson (TYS/KTYS)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#539]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='McGhee Tyson', city='Knoxville', country='United States', iata='TYS', icao='KTYS', x=-83.994028, y=35.810972, elevation=981, timezone=-5, dst='A' WHERE apid=3676;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Mc Ghee Tyson
    [city] => Knoxville
    [country] => United States
    [iata] => TYS
    [icao] => KTYS
    [x] => -83.994028
    [y] => 35.810972
    [elevation] => 981
    [apid] => 3676
    [uid] => 
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KTYS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KTYS%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='McGhee Tyson', city='Knoxville', country='United States', iata='TYS', icao='KTYS', x=-83.994028, y=35.810972, elevation=981, timezone=-5, dst='A' WHERE apid=3676;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Mc Ghee Tyson
    [city] => Knoxville
    [country] => United States
    [iata] => TYS
    [icao] => KTYS
    [x] => -83.994028
    [y] => 35.810972
    [elevation] => 981
    [apid] => 3676
    [uid] => 
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KTYS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KTYS%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='McGhee Tyson', city='Knoxville', country='United States', iata='TYS', icao='KTYS', x=-83.994028, y=35.810972, elevation=981, timezone=-5, dst='A' WHERE apid=3676;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Mc Ghee Tyson
    [city] => Knoxville
    [country] => United States
    [iata] => TYS
    [icao] => KTYS
    [x] => -83.994028
    [y] => 35.810972
    [elevation] => 981
    [apid] => 3676
    [uid] => 
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KTYS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KTYS%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='McGhee Tyson', city='Knoxville', country='United States', iata='TYS', icao='KTYS', x=-83.994028, y=35.810972, elevation=981, timezone=-5, dst='A' WHERE apid=3676;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Mc Ghee Tyson
    [city] => Knoxville
    [country] => United States
    [iata] => TYS
    [icao] => KTYS
    [x] => -83.994028
    [y] => 35.810972
    [elevation] => 981
    [apid] => 3676
    [uid] => 
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KTYS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KTYS%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='McGhee Tyson', city='Knoxville', country='United States', iata='TYS', icao='KTYS', x=-83.994028, y=35.810972, elevation=981, timezone=-5, dst='A' WHERE apid=3676;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Mc Ghee Tyson
    [city] => Knoxville
    [country] => United States
    [iata] => TYS
    [icao] => KTYS
    [x] => -83.994028
    [y] => 35.810972
    [elevation] => 981
    [apid] => 3676
    [uid] => 
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KTYS/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KTYS%20airport&btnI

**Comment by chrisrosset** [comment]
This airport has been updated.
