### ISSUE TITLE
Update airport Punta Gorda-Charlotte County Airport (PGD/KPGD)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#542]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Punta Gorda-Charlotte County Airport', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Charlotte County', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Charlotte County-Punta Gorda', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Charlotte County-Punta Gorda', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Charlotte County-Punta Gorda', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Punta Gorda - Charlotte County', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by Johnandbob:

UPDATE airports SET name='Punta Gorda-Charlotte County-', city='Punta Gorda', country='United States', iata='PGD', icao='KPGD', x=-81.990556, y=26.919722, elevation=26, timezone=-5, dst='A' WHERE apid=7056;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Charlotte County-Punta Gorda Airport
    [city] => Punta Gorda
    [country] => United States
    [iata] => PGD
    [icao] => KPGD
    [x] => -81.990556
    [y] => 26.919722
    [elevation] => 26
    [apid] => 7056
    [uid] => 3315
    [timezone] => -5
    [dst] => A
    [tz_id] => America/New_York
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/KPGD/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20KPGD%20airport&btnI

**Comment by chrisrosset** [comment]
The airport has been updated since the issue was raised.
