### ISSUE TITLE
Update airport Dublin Airport (DUB/EIDW)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#550]
New airport edit suggestion submitted by pilocik:

UPDATE airports SET name='Dublin Airport', city='Dublin', country='Ireland', iata='DUB', icao='EIDW', x=-6.270075, y=53.421333, elevation=242, timezone=0, dst='E' WHERE apid=599;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Dublin
    [city] => Dublin
    [country] => Ireland
    [iata] => DUB
    [icao] => EIDW
    [x] => -6.270075
    [y] => 53.421333
    [elevation] => 242
    [apid] => 599
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/Dublin
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EIDW/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EIDW%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by tmckenna119:

Array
(
    [apid] => 599
    [name] => Dublin Airport
    [city] => Dublin
    [country] => Ireland
    [iata] => DUB
    [icao] => EIDW
    [x] => -6.27007
    [y] => 53.421299
    [elevation] => 242
    [timezone] => 0
    [dst] => E
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Dublin Airport
    [city] => Dublin
    [country] => Ireland
    [iata] => DUB
    [icao] => EIDW
    [x] => -6.27007
    [y] => 53.421299
    [elevation] => 242
    [apid] => 599
    [uid] => 
    [timezone] => 0
    [dst] => E
    [tz_id] => Europe/Dublin
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EIDW/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EIDW%20airport&btnI

**Comment by chrisrosset** [comment]
The database and `airports.dat` (1c5c7861456bd62adc85bec105279fe42315ddad) have been updated with this since the issue was opened.

@reedy, could you please close?
