### ISSUE TITLE
LastPass does not play nice with OpenFlights autologin

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#551]
OpenFlights attempts to log in as soon as it detects a change to username/pw field contents.  However. this does not work well with LastPass; it looks like there's a race condition causing it to submit prematurely, causing the login to fail.

**Comment by SwedenGuy** [comment]
I've received email from LastPass. If you take the following actions, you can at least keep the LastPass extension loaded.

Go to the LastPass Vault > Account Settings > Never URLs
Add the URL to both of the following categories
- Never Fill Forms
- Never AutoLogin
- Never Show Context Icon

**Comment by jpatokal** [comment]
This is **finally** fixed.  Sorry for the delay!

**Comment by jpatokal** [comment]
Spoke too soon: the fix broke the janky autocomplete.  Sigh: fixing that too.

**Comment by jpatokal** [comment]
Fixed!
