### ISSUE TITLE
Is openflight death?

### ISSUE THREAD

**Issue by WilbertE** [jpatokal/openflights#561]
Hi guys,

When I see the revision log the last update is from 2014.
Is this source of information dead and are there any alternatives?

**Comment by jpatokal** [comment]
Actually the last commit is from 21 hours ago ;) https://github.com/jpatokal/openflights/commits/master

Our current source of route data is indeed "dead", but I'm currently working on bringing a replacement online.  Stay tuned!

**Comment by WilbertE** [comment]
You rule!

**Comment by michaelso** [comment]
@jpatokal I learnt that the old source you guys rely on isnt updating anymore (#330)
As I would like to build some route searching tools for my projects, I would to ask if you guys find any new data source?
I can help updating the route db as I would like to use it in my projects.

Thank you!
