### ISSUE TITLE
Could not sign in, keep getting error "Session expired. Please refresh and try again."

### ISSUE THREAD

**Issue by wangchun** [jpatokal/openflights#571]
This error has been there to me since yesterday. I have tried to clear cookies, change browsers, everything.

**Comment by cyraxx** [comment]
After debugging the JS a bit and looking through the PHP sources, it seems to me that the server-side session storage is broken. `map.php` sets `$_SESSION["challenge"]` which is sent to `login.php` via the login form and checked against the session value there. This check fails and causes the error message.

**Comment by jpatokal** [comment]
Thanks for the bug report, this should be fixed now.
