### ISSUE TITLE
Update airport Chopin (WAW/EPWA)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#585]
New airport edit suggestion submitted by paashaas:

UPDATE airports SET name='Chopin', city='Warsaw', country='Poland', iata='WAW', icao='EPWA', x=20.967122, y=52.16575, elevation=362, timezone=1, dst='E' WHERE apid=679;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Okecie
    [city] => Warsaw
    [country] => Poland
    [iata] => WAW
    [icao] => EPWA
    [x] => 20.967122
    [y] => 52.16575
    [elevation] => 362
    [apid] => 679
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Warsaw
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EPWA/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EPWA%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by paashaas:

UPDATE airports SET name='Chopin', city='Warsaw', country='Poland', iata='WAW', icao='EPWA', x=20.967122, y=52.16575, elevation=362, timezone=1, dst='E' WHERE apid=679;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Okecie
    [city] => Warsaw
    [country] => Poland
    [iata] => WAW
    [icao] => EPWA
    [x] => 20.967122
    [y] => 52.16575
    [elevation] => 362
    [apid] => 679
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Warsaw
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EPWA/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EPWA%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by paashaas:

UPDATE airports SET name='Chopin', city='Warsaw', country='Poland', iata='WAW', icao='EPWA', x=20.967122, y=52.16575, elevation=362, timezone=1, dst='E' WHERE apid=679;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Okecie
    [city] => Warsaw
    [country] => Poland
    [iata] => WAW
    [icao] => EPWA
    [x] => 20.967122
    [y] => 52.16575
    [elevation] => 362
    [apid] => 679
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Warsaw
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EPWA/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EPWA%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by paashaas:

UPDATE airports SET name='Chopin', city='Warsaw', country='Poland', iata='WAW', icao='EPWA', x=20.967122, y=52.16575, elevation=362, timezone=1, dst='E' WHERE apid=679;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Okecie
    [city] => Warsaw
    [country] => Poland
    [iata] => WAW
    [icao] => EPWA
    [x] => 20.967122
    [y] => 52.16575
    [elevation] => 362
    [apid] => 679
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Warsaw
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/EPWA/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20EPWA%20airport&btnI

**Comment by chrisrosset** [comment]
https://github.com/jpatokal/openflights/commit/5d623a6969a1adee7961cf1c9a8a212c4a784713
