### ISSUE TITLE
Autocomplete comboboxes are overriding keystrokes in text entry fields

### ISSUE THREAD

**Issue by NickMOrlando** [jpatokal/openflights#613]
On the New Flight tab, begin typing an airport name:

![image](https://cloud.githubusercontent.com/assets/360143/18723033/0a9c5f00-8005-11e6-90c7-cc395a1a4b1e.png)

As soon as the combobox of recommendations appear, typing any more characters causes the selected item in the combobox to shift up/down, instead of allowing the user to continue typing more characters into the textbox.

**Comment by NickMOrlando** [comment]
Generalized the title- this seems to be an issue with all combobox/autocomplete fields.

![image](https://cloud.githubusercontent.com/assets/360143/18723151/811f0b28-8005-11e6-8fdb-aa19df751a55.png)

**Comment by jpatokal** [comment]
Fixed!
