### ISSUE TITLE
Update needed on BLB airport

### ISSUE THREAD

**Issue by Floriaantasche** [jpatokal/openflights#637]
BLB airport is located in the sea (  8°32'43.06"N,  79°21'22.57"W).  ![image](https://cloud.githubusercontent.com/assets/24447381/20996910/018e66a4-bccf-11e6-95be-52662bfe5971.png)

On ourairports it is located correctly:
http://ourairports.com/airports/MPHO/

Correct coordinates are:
  8°55'2.61"N
 79°35'54.64"W

Regards,

Floriaan

**Comment by flukmanji** [comment]
There aren't any flight routes  showing from/to BLB in openflights.org

**Comment by reedy** [comment]
#828
