### ISSUE TITLE
Broken airports-extended.dat link in data.html

### ISSUE THREAD

**Issue by bbrewington** [jpatokal/openflights#668]
There is a broken link in [data.html commit f0dfee1 line 114](https://github.com/jpatokal/openflights/blob/f0dfee13e0077e104d1be9661cf0dfc4ab8a72de/data.html)

The link pointing to airports-extended.dat is broken

**Comment by reedy** [comment]
https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports-extended.dat seems to work fine
