### ISSUE TITLE
KML export does not include Timestamp/TimeSpan elements

### ISSUE THREAD

**Issue by jrbray1** [jpatokal/openflights#685]
When I do an KML export, the flights do not contain the KML elements TimeStamp or TimeSpan, which would be very useful when viewing in Google Earth, where you can setup a time slider to show a range of dates.

**Comment by reedy** [comment]
https://developers.google.com/kml/documentation/kmlreference#timespan
```
<TimeSpan>
        <begin>2020-01-01</begin>
        <end>2020-01-01</end>
</TimeSpan>
```

This seems relatively easy...

**Comment by reedy** [comment]
I presume the begin is the date the flight started, and the end is the end date...

Although,

>The dateTime is defined according to XML Schema time (see [XML Schema Part 2: Datatypes Second Edition](http://www.w3.org/TR/xmlschema-2/#isoformats)). The value can be expressed as yyyy-mm-ddThh:mm:ss.ssszzzzzz, where T is the separator between the date and the time, and the time zone is either Z (for UTC) or zzzzzz, which represents ±hh:mm in relation to UTC. Additionally, the value can be expressed as a date only. See [<TimeStamp>](https://developers.google.com/kml/documentation/kmlreference#timestamp) for examples.

Presumably, we can just use the whole timestamps.
