### ISSUE TITLE
Add HTTPS to openflights.org

### ISSUE THREAD

**Issue by DASPRiD** [jpatokal/openflights#715]
In times where browser vendors discourage the use of HTTP, especially for login and registration forms, it is a sane idea to upgrade the connection on openflights.org to HTTPS. I'd personally recommend using Lets Encrypt, and automatically redirecting any HTTP requests to HTTPS.

**Comment by jpatokal** [comment]
Dupe of issue #327 (yes, this has been open for too long!).
