### ISSUE TITLE
Map Display Issue

### ISSUE THREAD

**Issue by smullins99** [jpatokal/openflights#726]
Background images for map view appear to be breaking.
Issue occurs in both great/earth map views.
Issue occurs in multiple browsers (Chrome/IE11/Firefox)

![image](https://cloud.githubusercontent.com/assets/28397178/25709897/a683194a-30b8-11e7-87d5-f99858b3ea68.png)

**Comment by jpatokal** [comment]
As part of the HTTPS migration (issue #327), map tiles were also switched from HTTP to HTTPS.  Can you try shift-reloading to make sure you've got the latest code?

**Comment by smullins99** [comment]
Issue resolved! Thanks!
