### ISSUE TITLE
TripIt import not working

### ISSUE THREAD

**Issue by ADEY827** [jpatokal/openflights#730]
Tried to import from TripIt and does not work. Attempted this on Windows and IOS and with different browsers.

**Comment by jpatokal** [comment]
Thanks for the report -- I fixed a bug with loading jQuery that may have caused this.  Can you try again?

**Comment by ADEY827** [comment]
Hi

Thanks - yes working great now.

**Comment by pax** [comment]
Again, not working.

<img width="418" alt="screen shot 2017-08-21 at 22 56 34" src="https://user-images.githubusercontent.com/116795/29535813-04ecf468-86c4-11e7-9ace-5c5392c47925.png">

**Comment by jpatokal** [comment]
Please see issue #701.

**Comment by pax** [comment]
it works, thank you! 👍
