### ISSUE TITLE
How do I get my challenge code?

### ISSUE THREAD

**Issue by JGeraldoLima** [jpatokal/openflights#732]
I'm implementing an open Android app that suppose to use your REST API to list airports, only. I'm trying to test the URL request first, changing the args to see the results, but I'm always getting the same random airports list. Even when I've added hardcoded ```name``` and ```pw``` args, I got the same result. And I didn't find anything about it on the website.

Searching for an anwser, I saw #23 where @jpatokal said that we have to send properly challenge argument. But how do I get it? There's any URL that I can use to request it?

**Comment by jpatokal** [comment]
OpenFlights does not offer a public API.  The challenge token is intended for interactive user sessions.
