### ISSUE TITLE
Feature request: Debounce for Aircraft type autocompletion

### ISSUE THREAD

**Issue by tueksta** [jpatokal/openflights#734]
Currently editing the aircraft type is a mess, because the autosuggestions keep getting in the way unless you're a fast typer without any breaks. It drives people crazy when they're unsure which is the exact name/number of the plane. I suggest to use debounce with a moderate timer.

**Comment by jpatokal** [comment]
This should be fixed now!

**Comment by tueksta** [comment]
awesome, thank you!!
