### ISSUE TITLE
FlightMemory import fails

### ISSUE THREAD

**Issue by Mehdron** [jpatokal/openflights#799]
Here's the results:

OpenFlights: Import
Upload successful. Parsing...

Results
Tmpfile phpvm6n9f
Sorry, the file /var/www/openflights/import/phpvm6n9f does not appear contain FlightMemory FlightData.

Can provide HTML code if desired.  Exported from IE.

**Comment by reedy** [comment]
Have you been able to do this successfully recently?

**Comment by reedy** [comment]
Probably fixed by the next deployment (#1391)
