### ISSUE TITLE
Simpletest

### ISSUE THREAD

**Issue by oddball118** [jpatokal/openflights#821]
I get the following errors when trying to install:

  - Installing lastcraft/simpletest (1.1.0): Downloading (failed)    Failed to download lastcraft/simpletest from dist: The "https://api.github.com/repos/lox/simpletest/zipball/1c9db340b758919f16c46d496476432d94400955" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing lastcraft/simpletest (1.1.0): Cloning 1c9db340b7
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes

  [RuntimeException]
  Failed to clone https://github.com/lox/simpletest.git via https, ssh protocols, aborting.
  - https://github.com/lox/simpletest.git
    Cloning into '/var/www/openflights/vendor/lastcraft/simpletest'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/lox/simpletest.git/'
  - git@github.com:lox/simpletest.git
    Cloning into '/var/www/openflights/vendor/lastcraft/simpletest'...
    Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by erwista:

UPDATE airports SET name='Verona', city='Verona', country='Italy', iata=NULL, icao=NULL, x=10.982397, y=45.42903, elevation=194, timezone=1, dst='E' WHERE apid=10118;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Verona Porta Nuova
    [city] => Verona
    [country] => Italy
    [iata] => 
    [icao] => 
    [x] => 10.982397
    [y] => 45.42903
    [elevation] => 194
    [apid] => 10118
    [uid] => 20490
    [timezone] => 1
    [dst] => E
    [tz_id] => 
    [type] => port
    [source] => User
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by reedy** [comment]
Is this still broken?

**Comment by chrisrosset** [comment]
We have [new and updated installation notes](https://github.com/jpatokal/openflights/blob/master/INSTALL) as well as a Docker setup (#1206) that's about to be merged. These should make it much easier to run your own instance.
