### ISSUE TITLE
Selecting Boeing 787-8 as aircraft messes up the whole flight

### ISSUE THREAD

**Issue by Gnopps** [jpatokal/openflights#826]
If you enter a new flight and select "Boeing 787-8" as your aircraft type, then the flight becomes messed up. After having saved numbers are present in several fiels that were previously empty.

![image](https://user-images.githubusercontent.com/16313148/35214127-b343f2cc-ff92-11e7-9954-196c38baf7b6.png)

**Comment by drewguy** [comment]
Same problem, although selecting B787 doesn't seem to create these problems.

(And those are some bizarre alternatives in slots 2-5 of the above drop-down screen shot).

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by dben:

UPDATE airports SET name='LUX', city='LUX South Ari Atoll', country='Maldives', iata=NULL, icao=NULL, x=72.8962, y=3.4987, elevation=0, timezone=5, dst='N' WHERE apid=13196;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => LUX
    [city] => LUX South Ari Atoll
    [country] => Maldives
    [iata] => 
    [icao] => 
    [x] => 72.8962
    [y] => 3.4987
    [elevation] => 0
    [apid] => 13196
    [uid] => 1970
    [timezone] => 0
    [dst] => U
    [tz_id] => 
    [type] => 
    [source] => 
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by dben:

UPDATE airports SET name='LUX', city='LUX South Ari Atoll', country='Maldives', iata=NULL, icao=NULL, x=72.8962, y=3.4987, elevation=0, timezone=5, dst='N' WHERE apid=13196;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => LUX
    [city] => LUX South Ari Atoll
    [country] => Maldives
    [iata] => 
    [icao] => 
    [x] => 72.8962
    [y] => 3.4987
    [elevation] => 0
    [apid] => 13196
    [uid] => 1970
    [timezone] => 0
    [dst] => U
    [tz_id] => 
    [type] => 
    [source] => 
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports//pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20%20airport&btnI

**Comment by jpatokal** [comment]
This should now be fixed!  https://blog.openflights.org/2018/05/17/fixing-plane-autocomplete-and-releasing-aircraft-data/
