### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by SwedenGuy** [jpatokal/openflights#831]
Just getting a "loading..." screen.  Have tried to access the site with both Chrome and Safari.

**Comment by SwedenGuy** [comment]
Hmm. I have solved it.  LastPass is preventing it from displaying properly.  LastPass is the only extension I have in Safari. As soon as I disabled it, it displayed properly.  Very odd.

**Comment by jpatokal** [comment]
Yup, LastPass does not play nice with OpenFlights, see issue #551.
