### ISSUE TITLE
Track carbon emissions

### ISSUE THREAD

**Issue by tomfitzhenry** [jpatokal/openflights#838]
It'd be useful to see the carbon emissions of the flights I've taken, and how it compares to:
* estimates for the average amount of emissions per person in the same country as me
* estimates for `global carbon limit / world population`

Carbon emissions for a particular flight depends on:
* length (non-linearly)
* passenger class

**Comment by reedy** [comment]
Some overlap with https://github.com/jpatokal/openflights/issues/275

**Comment by tomfitzhenry** [comment]
Closing in favour of https://github.com/jpatokal/openflights/issues/275.
