### ISSUE TITLE
Possible to get airport size/popularity?

### ISSUE THREAD

**Issue by Frexuz** [jpatokal/openflights#907]
I'm looking to sort a search of airports. The type attribute having "small_airport", "medium_airport" and "large_airport" is not quite enough imo :)

![screenshot 2018-10-31 at 21 34 16](https://user-images.githubusercontent.com/49692/47791461-bea0ca00-dd54-11e8-926c-9ebee4b316ab.png)

I'd assume SFO to be first :) Is this information that you have available?

**Comment by jpatokal** [comment]
I'm afraid no: our airport data is sourced from http://ourairports.com/, and if they don't have it, we don't either.
