### ISSUE TITLE
missing attribution “© OpenStreetMap contributors”. on the (osm?) map?

### ISSUE THREAD

**Issue by my-na-me** [jpatokal/openflights#916]
Is there a missing  attribution  _“© OpenStreetMap contributors”_ information on the (osm?) map for webpage: https://openflights.org/?

For additional information please see here: https://www.openstreetmap.org/copyright/en

**Comment by jpatokal** [comment]
Hmm, interesting, attribution is provided in the code (see below) but this doesn't appear to be rendering on the map:

> Map tiles by <a href='http://cartodb.com'>CartoDB</a> (CC BY 3.0), data by <a href='/http://openstreetmap.com'>OSM</a> (ODbL)

(from https://github.com/jpatokal/openflights/blob/master/openflights.js#L130)

It looks like the [OpenLayers.Layer.XYZ](http://dev.openlayers.org/docs/files/OpenLayers/Layer/XYZ-js.html) object we're using may not support attributions.  Pull requests to update this welcome :)

**Comment by my-na-me** [comment]
@jpatokal 

Thanks for checking.

> It looks like the [OpenLayers.Layer.XYZ](http://dev.openlayers.org/docs/files/OpenLayers/Layer/XYZ-js.html) object we're using may not support attributions. Pull requests to update this welcome :)

Actually unfortunately i'm not a programmer & i can't tell anything about the [OpenLayers.Layer.XYZ](http://dev.openlayers.org/docs/files/OpenLayers/Layer/XYZ-js.html) layer. I saw in meantime your project is added to a [application list which lacking of proper attribution - wiki OpenStreetMap](https://wiki.openstreetmap.org/wiki/Lacking_proper_attribution) a long list of open and closed cases. Maybe you can find there any other (open source) application for which the attribution issue is already fixed and they did use similar technology and have a solution which you could just copy&paste to your project. :-)

**Comment by kmpoppe** [comment]
Hi @jpatokal and @my-na-me,
I came here because another page that I want to write to because of missing attribution also uses OpenLayers.XYZ - a quick look at their website in the examples gives a way on how to add attribution:

http://dev.openlayers.org/examples/attribution.html

Please use this as a reference on how to create the attribution you need to give for your project. Thanks :-)

Kai

**Comment by matkoniecz** [comment]
You are using OpenStreetMap data without attribution.

You even got pull request that fixes this - you have not bothered to even review it.

**Comment by reedy** [comment]
Possibly worth some attribution on https://openflights.org/about in the Credits section too

**Comment by matkoniecz** [comment]
I hope that it is sign that something is moving forward!

As long as you use OSM data you are legally obligated to show license clearly visible to users who view OSM-derived map. And no, deeply buried mention on "about" page is not sufficient.

Please, see https://www.openstreetmap.org/copyright if in doubt

**Comment by kmpoppe** [comment]
They asked in the PR how they could test the attribution, rather where it would be displayed and I answered that, so my guess is they are working on this problem right now @matkoniecz

**Comment by reedy** [comment]
> As long as you use OSM data you are legally obligated to show license clearly visible to users who view OSM-derived map. And no, deeply buried mention on "about" page is not sufficient.

Please note what I wrote:

> Possibly worth some attribution on https://openflights.org/about in the Credits section too

"too" meaning "as well as" not "instead of"; other similar data sources, attributions are mentioned in a couple of places and given credit. If we're going to fix it, we might aswell get it done right.

And yeah, I'm going to hopefully test the PR later today.

Don't worry, I'm very much aware of the importance of attribution.

**Comment by reedy** [comment]
Ok, so this isn't deployed yet, but https://github.com/jpatokal/openflights/commit/b82c1443501a7f80eabb0cf356d5402c8b114a39 brings the controls back to the map...

Which fixes the basic issue that @jpatokal highlighted above.

> Hmm, interesting, attribution is provided in the code (see below) but this doesn't appear to be rendering on the map:
> 
> > Map tiles by [CartoDB](http://cartodb.com) (CC BY 3.0), data by [OSM](/http://openstreetmap.com) (ODbL)
> 
> (from https://github.com/jpatokal/openflights/blob/master/openflights.js#L130)
> 
> It looks like the [OpenLayers.Layer.XYZ](http://dev.openlayers.org/docs/files/OpenLayers/Layer/XYZ-js.html) object we're using may not support attributions. Pull requests to update this welcome :)

When Jani is around, hopefully they can deploy the update.

As per my comments at https://github.com/jpatokal/openflights/pull/1037/files#r1174599252 too, I'm not 100% sure where the attribution for OSM needs to go in these cases.
![Screenshot 2023-04-23 at 17 03 36](https://user-images.githubusercontent.com/67615/233851295-4573f746-9161-4e62-bb04-9545657951c5.png)
![Screenshot 2023-04-23 at 17 03 39](https://user-images.githubusercontent.com/67615/233851296-a30c341a-4abb-47be-8c00-1a462786686f.png)
![Screenshot 2023-04-23 at 17 03 33](https://user-images.githubusercontent.com/67615/233851291-b7a81fac-92d7-463a-840a-fc6f43033241.png)

Does the one that says "data by OSM" actually resolve this in the broad sense?

I understand specific wording may be needed, as it differs from the PR at https://github.com/jpatokal/openflights/pull/1037/files

> Possibly worth some attribution on https://openflights.org/about in the Credits section too

I still want to do something around this too.. So will have a look at that next...

**Comment by reedy** [comment]
![Screenshot 2023-04-23 at 20 19 13](https://user-images.githubusercontent.com/67615/233860416-d65d4b73-5931-428f-a90b-8593d72b4069.png)

Must've been some testing when I was playing around.. Looks like I still neeed to fix the positioning!

**Comment by reedy** [comment]
![Screenshot 2023-04-23 at 21 08 55](https://user-images.githubusercontent.com/67615/233863165-51f3ad4a-7bbd-44b2-87e5-388be41b085f.png)
![Screenshot 2023-04-23 at 21 09 03](https://user-images.githubusercontent.com/67615/233863166-33421fac-fbe5-42c1-802d-8f0e5273526d.png)

Window size related....

**Comment by reedy** [comment]
Now I just need to fix the location of the `quicksearch` and the `qsmini`... And probably the context map too for ease. They need to be more sticky to the map, rather than relative to the window as a whole...

**Comment by reedy** [comment]
This is now live...
