### ISSUE TITLE
Issue When Importing FlightMemory Data

### ISSUE THREAD

**Issue by IADflyer** [jpatokal/openflights#943]
When importing FlightMemory data system says:
"Upload successful. Parsing...
Results
Tmpfile phpcyODpf"

Never get an option to import.  I tried recreating the HTML file with no luck.

**Comment by jpatokal** [comment]
Did you get this to work?  If yes, what was the issue?

**Comment by IADflyer** [comment]
Hi,

I got it to work only after selecting use historical airline names.

Thanks,
Brian
