### ISSUE TITLE
In airport search form offset is not working

### ISSUE THREAD

**Issue by redlabrat** [jpatokal/openflights#944]
If I try to load next page of airport search result remote returns the same page. So no matter which value of offset is send - the result is always first page.
I think `is_int($offset)` in **apsearch.php** is causing that error.

**Comment by Paul-DS** [comment]
Is someone working on this problem ?
As @redlabrat said, you should modify the line 198 of the file https://github.com/jpatokal/openflights/blob/master/php/apsearch.php

Replace

```
if(! $offset || !is_int($offset)) {
  $offset = 0;
}
```

by

```
if(! $offset || !ctype_digit($offset)) {
  $offset = 0;
}
```

The `$offset` variable is coming from the `$_POST["offset"]` which will always be a string, whatever his value.
The [is_int](https://www.php.net/manual/en/function.is-int.php) function checks the type of the variable, while the [ctype_digit](https://php.net/manual/en/function.ctype-digit.php) checks the value of the variable, whatever the type.

**Comment by jpatokal** [comment]
Thanks, I missed the original error report.  This should be fixed now, please try again!
