### ISSUE TITLE
CSV import not parsing airline code in Flight_Number field

### ISSUE THREAD

**Issue by glac13** [jpatokal/openflights#951]
I've been trying to upload flights with the 2-letter IATA code in the Flight_Number field (for example, WN323) which the spec says should work, but it never successfully parses. 

Tmpfile is phpRjBwGl

[testimport.txt](https://github.com/jpatokal/openflights/files/3118520/testimport.txt)

**Comment by glac13** [comment]
Looking at import.php, I think the issue is in check_airline, at line 168. The SQL is only executed in the Else condition, it is never executed if you find alphanumeric code in the flight number

**Comment by jpatokal** [comment]
A-ha, looks like this broke in commit 943ceccb66792d348939f707fe7385743395c470.  I'll try to fix this up.

**Comment by jpatokal** [comment]
This should be fixed now, please try again!
