### ISSUE TITLE
Opening and closing date

### ISSUE THREAD

**Issue by naturefund-falk** [jpatokal/openflights#956]
Are there any plans on adding fields for opening and closing dates for the airports?
Maybe the opening date is not so important, but the closing date is, as some of the airports on the list are already closed. I dont think that removing an airport would be a good idea, because maybe you want some historical routes.

**Comment by jpatokal** [comment]
No.  I don't have access to that data, and "closure" is not binary anyway: many closed airports are resurrected for passenger traffic (eg. DMK) or live on for non-passenger traffic (YMX, DIA, etc).
