### ISSUE TITLE
Update airport Oslo Lufthavn (OSL/ENGM)

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#959]
New airport edit suggestion submitted by maxelive:

Array
(
    [apid] => 644
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 11.0502
    [y] => 60.1210
    [elevation] => 681
    [timezone] => 1
    [dst] => E
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 0
    [y] => 0
    [elevation] => 0
    [apid] => 644
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Oslo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/ENGM/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20ENGM%20airport&btnI

**Comment by devmind-ua** [comment]
Seems the same issue for Johannesburg (JNB) airport. Coordinates were changed to [0, 0] for some reason. Probably related to 1b65d06c6f63f8395cf64f1a1e41a487f4f79b5d.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by iceman85:

Array
(
    [apid] => 644
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 11.1004
    [y] => 60.1939
    [elevation] => 681
    [timezone] => 1
    [dst] => E
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 0
    [y] => 0
    [elevation] => 0
    [apid] => 644
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Oslo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/ENGM/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20ENGM%20airport&btnI

**Comment by iceman85** [comment]
Took the info from GEN airport source already listed in OpenFlights in order to have further guidance to restore the original location of Oslo Gardermoen Lufthavn. (aka OSL)

**Comment by martinlechner** [comment]
The same issue with TOS (Tromso) airport. Lat/Lon shows as 0/0.

**Comment by jpatokal** [comment]
New airport edit suggestion submitted by jonstanley:

Array
(
    [apid] => 644
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 11.083889
    [y] => 60.202778
    [elevation] => 681
    [timezone] => 1
    [dst] => E
)
;

Existing, potentially conflicting airport information:

```
Array
(
    [name] => Oslo Lufthavn
    [city] => Oslo
    [country] => Norway
    [iata] => OSL
    [icao] => ENGM
    [x] => 0
    [y] => 0
    [elevation] => 0
    [apid] => 644
    [uid] => 
    [timezone] => 1
    [dst] => E
    [tz_id] => Europe/Oslo
    [type] => airport
    [source] => OurAirports
)

```

Cross-check this edit on other sites with compatible licensing:
- OurAirports: http://ourairports.com/airports/ENGM/pilot-info.html
- Wikipedia: http://www.google.com/search?q=wikipedia%20ENGM%20airport&btnI

**Comment by jpatokal** [comment]
Thanks for flagging, looks like these were caused by some junk entries in the latest OurAirports.  Corrected.
