### ISSUE TITLE
[Bug] Commas in airport data [sf#96]

### ISSUE THREAD

**Issue by jpatokal** [jpatokal/openflights#96]
**Reported by jpatokal on 2011-04-11 22:45 UTC**
Commas in elevation field should be stripped out.  Commas in lat/lon fields should be turned into decimal points.

**Comment by brouwer** [comment]
Commas in airport names also cause a problem for top 10. 
Under airports in the top 10 the data coming from the server is splitted by comma and then parseInt is used on a column index. 

That works only as long as the airport name does not contain a comma, e.g.
```
var input = ('Oslo Gardermoen Airport,OSL,101,644').split(',');
var output = parseInt(input[2]); //output is 101
```

But this fails
```
var input = ('Sandefjord Airport, Torp,TRF,17,664').split(',');
var output = parseInt(input[2]); //output is NaN

```
Code that breaks this is line 1745-1750 in [`openflights.js`](https://github.com/jpatokal/openflights/blob/master/openflights.js)

**Comment by jpatokal** [comment]
Thanks for the fix, although I'll be honest, that's a pretty hideous hack!  I'll accept it for now, but migrating the (equally hideous) backend code to use JSON instead of homebrew CSV would be a better solution...

**Comment by brouwer** [comment]
Yeah I know :) But hey it works. Also if you're ever gonna ~~waste~~ use time to migrate to JSON you might as well start from scratch with the whole thing. I'd be happy contribute. I love the idea of openflights, but both the UI and code could use a makeover
