### ISSUE TITLE
Istanbul Airport code and Istanbul Ataturk Airport code have been switched

### ISSUE THREAD

**Issue by protogonus** [jpatokal/openflights#963]
Correct Istanbul Airport code is now IST and the old Istanbul Ataturk Airport code is now ISL. Would you please reflect this change in the system? Thank you.

**Comment by jpatokal** [comment]
This change has already been made?   Note that the route data predates the change, so they're all still pointing to ISL (old IST), but this will be fixed in the next route update.

https://openflights.org/airport/IST

https://openflights.org/airport/ISL
