### ISSUE TITLE
737 NG's do not show as an option

### ISSUE THREAD

**Issue by 2sylbl** [jpatokal/openflights#964]
When attempting to enter a 737-600, -700, -800, or -900, none of those options appear in autocomplete, even after typing the -6, -7, etc.

**Comment by devmind-ua** [comment]
I confirm. NGs were in the list last year for sure.

**Comment by jpatokal** [comment]
D'oh, looks like this broke in the autocomplete changes earlier this year -- there are so many 737 variants that the ones lower down the list don't make the cut!

I'll take a look, but as an immediate workaround you can either enter short official codes like `736`, or just the final part of the designation like `900`.

**Comment by devmind-ua** [comment]
Thanks. I'm typing them in manually now to keep my list consistent :)

**Comment by jpatokal** [comment]
The previous autocomplete code was throwing away everything after the hyphen.  I've updated, try again now?

Also, I meant that you can enter those short codes in the autocomplete, and it will expand them to the full ones in the dropdown.

**Comment by devmind-ua** [comment]
Autocomplete works as expected now. Thanks a lot!

**Comment by 2sylbl** [comment]
This issue is recurring again - autocomplete failing to show anything above a 737-500 if you use the correct hyphenation.

**Comment by chrisrosset** [comment]
The back-end code still throws everything after a hyphen away when preparing the SQL query:
https://github.com/jpatokal/openflights/blob/f53e4522574e201796d5526b5f9e06e0ca506abb/php/autocomplete.php#L12-L16

**Comment by chrisrosset** [comment]
I shouldn't have re-opened this. Let's use the new issue.
